table Fact_Tx
	lineageTag: fact-tx

	column BookingDate
		dataType: dateTime
		lineageTag: cd63dc04-6988-4a22-8af8-87e4234d86f3
		summarizeBy: none
		sourceColumn: kpi_date

	column CountryCode
		dataType: string
		lineageTag: 7083df1f-2c7f-47e5-b908-12e21cc19dcb
		summarizeBy: none
		sourceColumn: issuer_country

	column Instrument
		dataType: string
		lineageTag: be167773-2892-45b7-b2b8-c3cf31969af9
		summarizeBy: none
		sourceColumn: instrument_type

	column TxCount
		dataType: int64
		lineageTag: 024eca18-99a3-4aac-9c27-1ab81d615ccd
		summarizeBy: sum
		sourceColumn: tx_count

	column TxValueEur
		dataType: double
		formatString: "€"#,0.00
		lineageTag: 7d41b64e-4c6c-4c22-9cda-4c03cfe6c9b2
		summarizeBy: sum
		sourceColumn: tx_value_eur

	column DeclineCount
		dataType: int64
		lineageTag: 95f9e78a-f090-426c-9c34-f0af04acb894
		summarizeBy: sum
		sourceColumn: decline_count

	column FraudCount
		dataType: int64
		lineageTag: 08c0ce54-58c2-45df-ae81-959a06aa6948
		summarizeBy: sum
		sourceColumn: fraud_count

	column FraudValueEur
		dataType: double
		formatString: "€"#,0.00
		lineageTag: aa2a7839-2004-4a9c-aeba-9baef20f2ba3
		summarizeBy: sum
		sourceColumn: fraud_value_eur

	column LossValueEur
		dataType: double
		formatString: "€"#,0.00
		lineageTag: eee42e05-eb7c-42f4-bed9-50984916aacd
		summarizeBy: sum
		sourceColumn: loss_value_eur

	partition Fact_Tx = m
		mode: import
		source = let Source = #table({"kpi_date","issuer_country","instrument_type","tx_count","tx_value_eur","decline_count","fraud_count","fraud_value_eur","loss_value_eur"},{{#datetime(2026,1,15,0,0,0),"SE","card",69184,2776160.54,1009,34,2943.41,2121.26},{#datetime(2026,1,15,0,0,0),"SE","credit_transfer",182964,9664608.7,2667,59,4625.64,3016.57},{#datetime(2026,1,15,0,0,0),"SE","direct_debit",46956,7045993.75,685,43,11261.82,7091.38},{#datetime(2026,1,15,0,0,0),"SE","e_money",112926,22690587.47,1646,115,48700.56,28543.41},{#datetime(2026,1,15,0,0,0),"SE","cash_withdrawal",80758,6391133.3,1177,31,4155.69,2466.78},{#datetime(2026,1,15,0,0,0),"NO","card",130165,20665494.77,1897,124,37347.6,31343.84},{#datetime(2026,1,15,0,0,0),"NO","credit_transfer",139230,7122177.07,2030,120,14432.11,8582.11},{#datetime(2026,1,15,0,0,0),"NO","direct_debit",90407,16222381.33,1318,45,12727.34,6133.52},{#datetime(2026,1,15,0,0,0),"NO","e_money",101024,21480647.42,1473,71,34485.98,17762.41},{#datetime(2026,1,15,0,0,0),"NO","cash_withdrawal",133132,10377498.45,1941,152,24199.39,16785.97},{#datetime(2026,1,15,0,0,0),"DK","card",84862,12262446.54,1237,60,13446.46,11028.2},{#datetime(2026,1,15,0,0,0),"DK","credit_transfer",186001,14884006.6,2711,184,18739.37,14592.74},{#datetime(2026,1,15,0,0,0),"DK","direct_debit",122694,14384495.04,1789,137,31116.9,22938.31},{#datetime(2026,1,15,0,0,0),"DK","e_money",95738,16214659.32,1396,107,32556.39,18099.79},{#datetime(2026,1,15,0,0,0),"DK","cash_withdrawal",104651,19645372.6,1526,101,33312.03,22765.88},{#datetime(2026,1,15,0,0,0),"FI","card",134895,10786306.13,1966,102,10751.09,5040.61},{#datetime(2026,1,15,0,0,0),"FI","credit_transfer",68743,4559893.02,1002,62,8123.78,4906.01},{#datetime(2026,1,15,0,0,0),"FI","direct_debit",196208,46933911.67,2860,230,127585.46,57999.38},{#datetime(2026,1,15,0,0,0),"FI","e_money",70029,12237611.56,1021,37,13146.54,6502.55},{#datetime(2026,1,15,0,0,0),"FI","cash_withdrawal",153971,10381085.06,2245,146,21021.97,17632.29},{#datetime(2026,1,15,0,0,0),"EE","card",86832,12076138.11,1266,74,23610.52,15419.21},{#datetime(2026,1,15,0,0,0),"EE","credit_transfer",92143,6112034.09,1343,72,10565.33,6995.74},{#datetime(2026,1,15,0,0,0),"EE","direct_debit",40149,6334855.35,585,16,4220.71,3562.82},{#datetime(2026,1,15,0,0,0),"EE","e_money",120612,10141988.52,1758,97,10622.91,7890.3},{#datetime(2026,1,15,0,0,0),"EE","cash_withdrawal",58143,13691910.25,848,24,11629.33,9637.68},{#datetime(2026,2,15,0,0,0),"SE","card",83287,7440578.15,1100,66,8709.46,5798.04},{#datetime(2026,2,15,0,0,0),"SE","credit_transfer",92730,16798460.44,1225,98,29903.68,24217.36},{#datetime(2026,2,15,0,0,0),"SE","direct_debit",158354,9470497.18,2092,112,13172.51,7140.1},{#datetime(2026,2,15,0,0,0),"SE","e_money",97728,3564542.99,1291,40,1884.23,871.57},{#datetime(2026,2,15,0,0,0),"SE","cash_withdrawal",126619,6270901.79,1673,135,9850.13,4953.87},{#datetime(2026,2,15,0,0,0),"NO","card",189695,29046741.12,2506,162,42803.99,20876.8},{#datetime(2026,2,15,0,0,0),"NO","credit_transfer",152997,16467220.28,2021,194,26461.34,18824.12},{#datetime(2026,2,15,0,0,0),"NO","direct_debit",65799,3120556.94,869,79,5031.97,2650.02},{#datetime(2026,2,15,0,0,0),"NO","e_money",180584,22927987.93,2386,117,22615.31,18528.86},{#datetime(2026,2,15,0,0,0),"NO","cash_withdrawal",156164,31333457.09,2063,71,29090.17,19380.89},{#datetime(2026,2,15,0,0,0),"DK","card",43868,10249505.2,580,54,17960.62,11571.24},{#datetime(2026,2,15,0,0,0),"DK","credit_transfer",96032,20383111.86,1269,51,12953.88,7852.24},{#datetime(2026,2,15,0,0,0),"DK","direct_debit",159277,14888591.49,2104,179,37192.94,26583.6},{#datetime(2026,2,15,0,0,0),"DK","e_money",167577,11182974.46,2214,231,30141.8,20100.91},{#datetime(2026,2,15,0,0,0),"DK","cash_withdrawal",122209,5709467.72,1614,107,11581.18,5940.83},{#datetime(2026,2,15,0,0,0),"FI","card",173124,8902529.55,2287,170,18155.16,9877.88},{#datetime(2026,2,15,0,0,0),"FI","credit_transfer",71427,16287299.25,944,68,19533.72,9430.75},{#datetime(2026,2,15,0,0,0),"FI","direct_debit",193006,29119108.47,2550,122,37969.28,21857.91},{#datetime(2026,2,15,0,0,0),"FI","e_money",109629,12731884.35,1448,73,13688.16,10276.32},{#datetime(2026,2,15,0,0,0),"FI","cash_withdrawal",59016,2178261.01,780,55,2722.48,1810.59},{#datetime(2026,2,15,0,0,0),"EE","card",172614,15425837.4,2280,222,46450.97,27768.9},{#datetime(2026,2,15,0,0,0),"EE","credit_transfer",81352,10154994.23,1075,54,16796.93,12981.33},{#datetime(2026,2,15,0,0,0),"EE","direct_debit",178658,6539550.44,2360,119,8997.12,7427.77},{#datetime(2026,2,15,0,0,0),"EE","e_money",75203,6709274.29,994,85,10627.44,5980.09},{#datetime(2026,2,15,0,0,0),"EE","cash_withdrawal",95215,17339651.1,1258,97,27192.41,17550.32},{#datetime(2026,3,15,0,0,0),"SE","card",53316,2874861.95,631,27,1755.58,1331.52},{#datetime(2026,3,15,0,0,0),"SE","credit_transfer",108670,7403068.24,1287,94,12371.16,6120.63},{#datetime(2026,3,15,0,0,0),"SE","direct_debit",79073,11611554.49,937,61,12387.74,6205.99},{#datetime(2026,3,15,0,0,0),"SE","e_money",120808,13259108.15,1431,131,18055.49,10709.14},{#datetime(2026,3,15,0,0,0),"SE","cash_withdrawal",105412,18101490.86,1249,78,31419.58,26377.83},{#datetime(2026,3,15,0,0,0),"NO","card",80515,18098289.21,954,33,16423.39,8553.65},{#datetime(2026,3,15,0,0,0),"NO","credit_transfer",148080,5935224.72,1754,82,7922.57,6107.46},{#datetime(2026,3,15,0,0,0),"NO","direct_debit",105055,9422926.13,1244,38,7998.98,6346.69},{#datetime(2026,3,15,0,0,0),"NO","e_money",98309,7462875.1,1164,56,9622.15,7683.57},{#datetime(2026,3,15,0,0,0),"NO","cash_withdrawal",98438,3922873.32,1166,54,5005.61,4188.47},{#datetime(2026,3,15,0,0,0),"DK","card",113170,12107487.52,1340,96,23587.94,13739.04},{#datetime(2026,3,15,0,0,0),"DK","credit_transfer",47235,2770099.37,559,20,2813.59,1564.88},{#datetime(2026,3,15,0,0,0),"DK","direct_debit",68417,10761796.19,810,63,17618.04,14864.24},{#datetime(2026,3,15,0,0,0),"DK","e_money",70315,8013453.46,833,34,8337.1,3757.34},{#datetime(2026,3,15,0,0,0),"DK","cash_withdrawal",181151,31847381.1,2146,162,41514.67,25843.67},{#datetime(2026,3,15,0,0,0),"FI","card",126559,20597079.73,1499,48,18693.48,12204.02},{#datetime(2026,3,15,0,0,0),"FI","credit_transfer",147057,14980328.29,1742,109,16099.86,11527.04},{#datetime(2026,3,15,0,0,0),"FI","direct_debit",139390,24232976.42,1651,111,30681.1,20531.02},{#datetime(2026,3,15,0,0,0),"FI","e_money",40106,3902087.79,475,37,7213.12,4175.67},{#datetime(2026,3,15,0,0,0),"FI","cash_withdrawal",155811,19576523.9,1845,105,31380.51,24113.1},{#datetime(2026,3,15,0,0,0),"EE","card",84483,14367550.94,1001,70,23834.83,11616.02},{#datetime(2026,3,15,0,0,0),"EE","credit_transfer",101569,17563627.61,1203,45,9528.67,5221.11},{#datetime(2026,3,15,0,0,0),"EE","direct_debit",164554,26379843.36,1949,108,40763.33,27730},{#datetime(2026,3,15,0,0,0),"EE","e_money",140657,19178204.94,1666,116,19175.79,14389.24},{#datetime(2026,3,15,0,0,0),"EE","cash_withdrawal",67941,13219700.48,805,64,26335.43,16744.6},{#datetime(2026,4,15,0,0,0),"SE","card",186120,16022260.68,1950,72,13912.63,9975.78},{#datetime(2026,4,15,0,0,0),"SE","credit_transfer",186518,29295957.98,1954,112,35107.37,25899.05},{#datetime(2026,4,15,0,0,0),"SE","direct_debit",172324,21106563.21,1806,66,11293.21,8973.56},{#datetime(2026,4,15,0,0,0),"SE","e_money",157983,13923715.97,1655,75,14583.72,9603.67},{#datetime(2026,4,15,0,0,0),"SE","cash_withdrawal",102716,9377198.03,1076,31,4414.13,2550.86},{#datetime(2026,4,15,0,0,0),"NO","card",181597,9355590.48,1903,64,4604.22,2465.93},{#datetime(2026,4,15,0,0,0),"NO","credit_transfer",148755,17636076.07,1559,55,9510.81,5878.22},{#datetime(2026,4,15,0,0,0),"NO","direct_debit",193112,44211585.94,2023,115,51159.14,32782.36},{#datetime(2026,4,15,0,0,0),"NO","e_money",132211,12720759.86,1385,79,17421.04,11590.01},{#datetime(2026,4,15,0,0,0),"NO","cash_withdrawal",183165,36444884.97,1919,74,22809.01,14694.86},{#datetime(2026,4,15,0,0,0),"DK","card",141936,14748081,1487,51,7545.56,4806.19},{#datetime(2026,4,15,0,0,0),"DK","credit_transfer",73456,17339142.28,770,44,20565.17,14708.2},{#datetime(2026,4,15,0,0,0),"DK","direct_debit",62006,10340348.61,650,24,5070.74,3050.77},{#datetime(2026,4,15,0,0,0),"DK","e_money",95485,12242452.84,1000,57,11372.95,9445.02},{#datetime(2026,4,15,0,0,0),"DK","cash_withdrawal",150510,13051574.59,1577,26,4231.88,3596.94},{#datetime(2026,4,15,0,0,0),"FI","card",131740,10666400.76,1380,84,8472.5,3917.79},{#datetime(2026,4,15,0,0,0),"FI","credit_transfer",104823,7952809.89,1098,25,2543.42,1825.62},{#datetime(2026,4,15,0,0,0),"FI","direct_debit",187841,43070098.5,1968,54,20821.72,14416.07},{#datetime(2026,4,15,0,0,0),"FI","e_money",70024,13615980.3,734,22,8292.89,6813.06},{#datetime(2026,4,15,0,0,0),"FI","cash_withdrawal",190941,33196275.5,2001,68,25274.42,12141.8},{#datetime(2026,4,15,0,0,0),"EE","card",103661,5793589.2,1086,60,6649.78,3314.4},{#datetime(2026,4,15,0,0,0),"EE","credit_transfer",188355,36812147.54,1974,70,23155.95,15106.58},{#datetime(2026,4,15,0,0,0),"EE","direct_debit",129451,4866540.87,1356,52,3439.8,2046.25},{#datetime(2026,4,15,0,0,0),"EE","e_money",160517,28892782.62,1682,84,37167.26,20740.56},{#datetime(2026,4,15,0,0,0),"EE","cash_withdrawal",181078,35093187.53,1897,103,39203.84,22695.96},{#datetime(2026,5,15,0,0,0),"SE","card",104355,21424066.77,951,64,19877.65,12639.87},{#datetime(2026,5,15,0,0,0),"SE","credit_transfer",199994,34394695.42,1822,83,23120.94,14913.46},{#datetime(2026,5,15,0,0,0),"SE","direct_debit",133015,26410877.54,1212,81,34035.24,19077},{#datetime(2026,5,15,0,0,0),"SE","e_money",42661,6011301.21,389,12,2999.67,2015.99},{#datetime(2026,5,15,0,0,0),"SE","cash_withdrawal",102999,18187039.63,938,43,16760.43,8166.04},{#datetime(2026,5,15,0,0,0),"NO","card",98090,11565029.88,894,49,9757.15,6550.84},{#datetime(2026,5,15,0,0,0),"NO","credit_transfer",130113,15903488.4,1185,43,11137.5,6218.81},{#datetime(2026,5,15,0,0,0),"NO","direct_debit",105903,8711612.39,965,34,6084.25,5052.07},{#datetime(2026,5,15,0,0,0),"NO","e_money",88535,6575131.41,807,27,3924.6,2959.48},{#datetime(2026,5,15,0,0,0),"NO","cash_withdrawal",196445,18272279.45,1790,52,7243.81,3779.65},{#datetime(2026,5,15,0,0,0),"DK","card",43708,7873724.75,398,8,1794.46,1017.2},{#datetime(2026,5,15,0,0,0),"DK","credit_transfer",73103,12117793.01,666,16,3159.65,1781.21},{#datetime(2026,5,15,0,0,0),"DK","direct_debit",165492,20735502.78,1508,32,9689.78,6212.03},{#datetime(2026,5,15,0,0,0),"DK","e_money",57129,6692378.17,521,27,4080.36,2079.67},{#datetime(2026,5,15,0,0,0),"DK","cash_withdrawal",187545,43054847.56,1709,55,24252.95,14951.2},{#datetime(2026,5,15,0,0,0),"FI","card",196271,38685381.15,1788,85,29754.19,18658.51},{#datetime(2026,5,15,0,0,0),"FI","credit_transfer",194278,46229695.11,1770,93,44064.39,32873.61},{#datetime(2026,5,15,0,0,0),"FI","direct_debit",94470,15420393.01,861,20,4835.6,3243.71},{#datetime(2026,5,15,0,0,0),"FI","e_money",81034,2880639.02,738,38,2105.03,1142.17},{#datetime(2026,5,15,0,0,0),"FI","cash_withdrawal",114112,20438879.83,1040,58,25040.68,19159.4},{#datetime(2026,5,15,0,0,0),"EE","card",194609,33189110.01,1773,74,24046.33,17050.15},{#datetime(2026,5,15,0,0,0),"EE","credit_transfer",109633,22415496.05,999,27,8973.76,6726.58},{#datetime(2026,5,15,0,0,0),"EE","direct_debit",189214,42354507.25,1724,76,27190.19,16613.3},{#datetime(2026,5,15,0,0,0),"EE","e_money",111367,15323742.41,1015,23,3953.79,2462.47},{#datetime(2026,5,15,0,0,0),"EE","cash_withdrawal",124494,19764828.83,1134,35,11443.69,9088.66},{#datetime(2026,6,15,0,0,0),"SE","card",193910,44582078.26,1502,85,30135.66,14046.01},{#datetime(2026,6,15,0,0,0),"SE","credit_transfer",85925,11295070.56,665,46,8754.36,5989.14},{#datetime(2026,6,15,0,0,0),"SE","direct_debit",168902,39465020.33,1308,54,20448.21,10057.25},{#datetime(2026,6,15,0,0,0),"SE","e_money",82159,8430314.54,636,22,5417.93,4201.2},{#datetime(2026,6,15,0,0,0),"SE","cash_withdrawal",184204,7832890.43,1427,47,2691.54,2042.94},{#datetime(2026,6,15,0,0,0),"NO","card",174898,35698444.19,1354,91,33557.14,15828.29},{#datetime(2026,6,15,0,0,0),"NO","credit_transfer",175905,19202628.63,1362,73,17424.21,9259.63},{#datetime(2026,6,15,0,0,0),"NO","direct_debit",183974,11380210.7,1425,97,10993.08,5073.83},{#datetime(2026,6,15,0,0,0),"NO","e_money",199612,39694705.65,1546,56,13454.28,8250.11},{#datetime(2026,6,15,0,0,0),"NO","cash_withdrawal",98903,23579732.61,766,34,10906.36,8538.12},{#datetime(2026,6,15,0,0,0),"DK","card",170646,38599080.38,1322,77,30235.03,19441.11},{#datetime(2026,6,15,0,0,0),"DK","credit_transfer",163789,13916305.48,1268,51,10337.23,6753.27},{#datetime(2026,6,15,0,0,0),"DK","direct_debit",75784,16075720.53,587,37,13547.56,11159.12},{#datetime(2026,6,15,0,0,0),"DK","e_money",173100,15539255.54,1341,80,16377.91,11169.23},{#datetime(2026,6,15,0,0,0),"DK","cash_withdrawal",168356,35755181.6,1304,59,20598.25,15554.75},{#datetime(2026,6,15,0,0,0),"FI","card",138883,17825028.42,1076,31,8490.95,5762.96},{#datetime(2026,6,15,0,0,0),"FI","credit_transfer",101226,21306317.75,784,29,10888.36,8878.06},{#datetime(2026,6,15,0,0,0),"FI","direct_debit",139937,15973268.99,1084,70,19790.85,12827.07},{#datetime(2026,6,15,0,0,0),"FI","e_money",49704,3026003.64,385,14,1134.83,894.27},{#datetime(2026,6,15,0,0,0),"FI","cash_withdrawal",66138,9445827.36,512,30,7413.46,5277.74},{#datetime(2026,6,15,0,0,0),"EE","card",80464,4050540.93,623,21,2102.21,1280.23},{#datetime(2026,6,15,0,0,0),"EE","credit_transfer",61054,12797644.02,473,31,11150.51,6430.1},{#datetime(2026,6,15,0,0,0),"EE","direct_debit",167912,35906053.33,1300,29,12524.11,10249.38},{#datetime(2026,6,15,0,0,0),"EE","e_money",99634,18739870.64,772,18,6988.35,5583.91},{#datetime(2026,6,15,0,0,0),"EE","cash_withdrawal",156307,10801561.05,1210,24,2707.04,1278.94}}), Typed = Table.TransformColumnTypes(Source,{{"kpi_date", type datetime},{"issuer_country", type text},{"instrument_type", type text},{"tx_count", Int64.Type},{"tx_value_eur", type number},{"decline_count", Int64.Type},{"fraud_count", Int64.Type},{"fraud_value_eur", type number},{"loss_value_eur", type number}}) in Typed

