table Fact_Tx
	lineageTag: fact-tx

	column BookingDate
		dataType: dateTime
		lineageTag: cd63dc04-6988-4a22-8af8-87e4234d86f3
		summarizeBy: none
		sourceColumn: kpi_date

	column CountryCode
		dataType: string
		lineageTag: 7083df1f-2c7f-47e5-b908-12e21cc19dcb
		summarizeBy: none
		sourceColumn: issuer_country

	column Instrument
		dataType: string
		lineageTag: be167773-2892-45b7-b2b8-c3cf31969af9
		summarizeBy: none
		sourceColumn: instrument_type

	column TxCount
		dataType: int64
		lineageTag: 024eca18-99a3-4aac-9c27-1ab81d615ccd
		summarizeBy: sum
		sourceColumn: tx_count

	column TxValueEur
		dataType: double
		formatString: "€"#,0.00
		lineageTag: 7d41b64e-4c6c-4c22-9cda-4c03cfe6c9b2
		summarizeBy: sum
		sourceColumn: tx_value_eur

	column DeclineCount
		dataType: int64
		lineageTag: 95f9e78a-f090-426c-9c34-f0af04acb894
		summarizeBy: sum
		sourceColumn: decline_count

	column FraudCount
		dataType: int64
		lineageTag: 08c0ce54-58c2-45df-ae81-959a06aa6948
		summarizeBy: sum
		sourceColumn: fraud_count

	column FraudValueEur
		dataType: double
		formatString: "€"#,0.00
		lineageTag: aa2a7839-2004-4a9c-aeba-9baef20f2ba3
		summarizeBy: sum
		sourceColumn: fraud_value_eur

	column LossValueEur
		dataType: double
		formatString: "€"#,0.00
		lineageTag: eee42e05-eb7c-42f4-bed9-50984916aacd
		summarizeBy: sum
		sourceColumn: loss_value_eur

	partition Fact_Tx = m
		mode: import
		source = let Source = #table({"kpi_date","issuer_country","instrument_type","tx_count","tx_value_eur","decline_count","fraud_count","fraud_value_eur","loss_value_eur"},{{#datetime(2025,1,15,0,0,0),"SE","card",69184,2776160.54,567,34,2943.41,2121.26},{#datetime(2025,1,15,0,0,0),"SE","credit_transfer",182964,9664608.7,1715,59,4625.64,3016.57},{#datetime(2025,1,15,0,0,0),"SE","direct_debit",46956,7045993.75,550,43,11261.82,7091.38},{#datetime(2025,1,15,0,0,0),"SE","e_money",112926,22690587.47,683,115,48700.56,28543.41},{#datetime(2025,1,15,0,0,0),"SE","cash_withdrawal",80758,6391133.3,977,31,4155.69,2466.78},{#datetime(2025,1,15,0,0,0),"NO","card",130165,20665494.77,1621,124,37347.6,31343.84},{#datetime(2025,1,15,0,0,0),"NO","credit_transfer",139230,7122177.07,1161,120,14432.11,8582.11},{#datetime(2025,1,15,0,0,0),"NO","direct_debit",90407,16222381.33,575,45,12727.34,6133.52},{#datetime(2025,1,15,0,0,0),"NO","e_money",101024,21480647.42,913,71,34485.98,17762.41},{#datetime(2025,1,15,0,0,0),"NO","cash_withdrawal",133132,10377498.45,1083,152,24199.39,16785.97},{#datetime(2025,1,15,0,0,0),"DK","card",84862,12262446.54,675,60,13446.46,11028.2},{#datetime(2025,1,15,0,0,0),"DK","credit_transfer",186001,14884006.6,1598,184,18739.37,14592.74},{#datetime(2025,1,15,0,0,0),"DK","direct_debit",122694,14384495.04,801,137,31116.9,22938.31},{#datetime(2025,1,15,0,0,0),"DK","e_money",95738,16214659.32,877,107,32556.39,18099.79},{#datetime(2025,1,15,0,0,0),"DK","cash_withdrawal",104651,19645372.6,1079,101,33312.03,22765.88},{#datetime(2025,1,15,0,0,0),"FI","card",134895,10786306.13,1885,102,10751.09,5040.61},{#datetime(2025,1,15,0,0,0),"FI","credit_transfer",68743,4559893.02,500,62,8123.78,4906.01},{#datetime(2025,1,15,0,0,0),"FI","direct_debit",196208,46933911.67,2007,230,127585.46,57999.38},{#datetime(2025,1,15,0,0,0),"FI","e_money",70029,12237611.56,721,37,13146.54,6502.55},{#datetime(2025,1,15,0,0,0),"FI","cash_withdrawal",153971,10381085.06,927,146,21021.97,17632.29},{#datetime(2025,1,15,0,0,0),"EE","card",86832,12076138.11,594,74,23610.52,15419.21},{#datetime(2025,1,15,0,0,0),"EE","credit_transfer",92143,6112034.09,1114,72,10565.33,6995.74},{#datetime(2025,1,15,0,0,0),"EE","direct_debit",40149,6334855.35,397,16,4220.71,3562.82},{#datetime(2025,1,15,0,0,0),"EE","e_money",120612,10141988.52,956,97,10622.91,7890.3},{#datetime(2025,1,15,0,0,0),"EE","cash_withdrawal",58143,13691910.25,596,24,11629.33,9637.68},{#datetime(2025,2,15,0,0,0),"SE","card",83287,7440578.15,1081,56,7380.89,4913.59},{#datetime(2025,2,15,0,0,0),"SE","credit_transfer",92730,16798460.44,852,83,25342.08,20523.17},{#datetime(2025,2,15,0,0,0),"SE","direct_debit",158354,9470497.18,1234,95,11163.13,6050.93},{#datetime(2025,2,15,0,0,0),"SE","e_money",97728,3564542.99,1139,34,1596.8,738.62},{#datetime(2025,2,15,0,0,0),"SE","cash_withdrawal",126619,6270901.79,1000,114,8347.56,4198.19},{#datetime(2025,2,15,0,0,0),"NO","card",189695,29046741.12,1506,137,36274.53,17692.19},{#datetime(2025,2,15,0,0,0),"NO","credit_transfer",152997,16467220.28,1421,164,22424.84,15952.63},{#datetime(2025,2,15,0,0,0),"NO","direct_debit",65799,3120556.94,778,67,4264.38,2245.78},{#datetime(2025,2,15,0,0,0),"NO","e_money",180584,22927987.93,1692,99,19165.5,15702.41},{#datetime(2025,2,15,0,0,0),"NO","cash_withdrawal",156164,31333457.09,2006,60,24652.66,16424.47},{#datetime(2025,2,15,0,0,0),"DK","card",43868,10249505.2,588,46,15220.85,9806.13},{#datetime(2025,2,15,0,0,0),"DK","credit_transfer",96032,20383111.86,1269,43,10977.85,6654.43},{#datetime(2025,2,15,0,0,0),"DK","direct_debit",159277,14888591.49,1843,152,31519.41,22528.45},{#datetime(2025,2,15,0,0,0),"DK","e_money",167577,11182974.46,1403,196,25543.87,17034.65},{#datetime(2025,2,15,0,0,0),"DK","cash_withdrawal",122209,5709467.72,1304,91,9814.55,5034.6},{#datetime(2025,2,15,0,0,0),"FI","card",173124,8902529.55,1296,144,15385.71,8371.08},{#datetime(2025,2,15,0,0,0),"FI","credit_transfer",71427,16287299.25,754,58,16553.98,7992.15},{#datetime(2025,2,15,0,0,0),"FI","direct_debit",193006,29119108.47,1646,103,32177.32,18523.63},{#datetime(2025,2,15,0,0,0),"FI","e_money",109629,12731884.35,1246,62,11600.12,8708.74},{#datetime(2025,2,15,0,0,0),"FI","cash_withdrawal",59016,2178261.01,647,47,2307.18,1534.4},{#datetime(2025,2,15,0,0,0),"EE","card",172614,15425837.4,2324,188,39365.19,23532.94},{#datetime(2025,2,15,0,0,0),"EE","credit_transfer",81352,10154994.23,841,46,14234.67,11001.12},{#datetime(2025,2,15,0,0,0),"EE","direct_debit",178658,6539550.44,2239,101,7624.67,6294.71},{#datetime(2025,2,15,0,0,0),"EE","e_money",75203,6709274.29,986,72,9006.3,5067.87},{#datetime(2025,2,15,0,0,0),"EE","cash_withdrawal",95215,17339651.1,726,82,23044.39,14873.14},{#datetime(2025,3,15,0,0,0),"SE","card",53316,2874861.95,500,29,1883.67,1428.67},{#datetime(2025,3,15,0,0,0),"SE","credit_transfer",108670,7403068.24,1036,101,13273.82,6567.22},{#datetime(2025,3,15,0,0,0),"SE","direct_debit",79073,11611554.49,1002,65,13291.61,6658.81},{#datetime(2025,3,15,0,0,0),"SE","e_money",120808,13259108.15,1626,141,19372.9,11490.53},{#datetime(2025,3,15,0,0,0),"SE","cash_withdrawal",105412,18101490.86,930,84,33712.1,28302.48},{#datetime(2025,3,15,0,0,0),"NO","card",80515,18098289.21,635,35,17621.72,9177.76},{#datetime(2025,3,15,0,0,0),"NO","credit_transfer",148080,5935224.72,1761,88,8500.64,6553.09},{#datetime(2025,3,15,0,0,0),"NO","direct_debit",105055,9422926.13,1292,41,8582.62,6809.77},{#datetime(2025,3,15,0,0,0),"NO","e_money",98309,7462875.1,1312,60,10324.23,8244.2},{#datetime(2025,3,15,0,0,0),"NO","cash_withdrawal",98438,3922873.32,742,58,5370.84,4494.08},{#datetime(2025,3,15,0,0,0),"DK","card",113170,12107487.52,1140,103,25309.03,14741.5},{#datetime(2025,3,15,0,0,0),"DK","credit_transfer",47235,2770099.37,650,21,3018.88,1679.06},{#datetime(2025,3,15,0,0,0),"DK","direct_debit",68417,10761796.19,599,68,18903.53,15948.8},{#datetime(2025,3,15,0,0,0),"DK","e_money",70315,8013453.46,746,37,8945.41,4031.49},{#datetime(2025,3,15,0,0,0),"DK","cash_withdrawal",181151,31847381.1,2449,174,44543.78,27729.35},{#datetime(2025,3,15,0,0,0),"FI","card",126559,20597079.73,1431,52,20057.44,13094.48},{#datetime(2025,3,15,0,0,0),"FI","credit_transfer",147057,14980328.29,1702,117,17274.58,12368.11},{#datetime(2025,3,15,0,0,0),"FI","direct_debit",139390,24232976.42,1843,119,32919.74,22029.06},{#datetime(2025,3,15,0,0,0),"FI","e_money",40106,3902087.79,308,40,7739.42,4480.35},{#datetime(2025,3,15,0,0,0),"FI","cash_withdrawal",155811,19576523.9,1201,113,33670.18,25872.5},{#datetime(2025,3,15,0,0,0),"EE","card",84483,14367550.94,698,75,25573.93,12463.58},{#datetime(2025,3,15,0,0,0),"EE","credit_transfer",101569,17563627.61,791,48,10223.93,5602.07},{#datetime(2025,3,15,0,0,0),"EE","direct_debit",164554,26379843.36,1998,116,43737.61,29753.31},{#datetime(2025,3,15,0,0,0),"EE","e_money",140657,19178204.94,1118,125,20574.95,15439.15},{#datetime(2025,3,15,0,0,0),"EE","cash_withdrawal",67941,13219700.48,526,69,28256.99,17966.36},{#datetime(2025,4,15,0,0,0),"SE","card",186120,16022260.68,2379,132,25474.73,18266.17},{#datetime(2025,4,15,0,0,0),"SE","credit_transfer",186518,29295957.98,2536,205,64283.4,47422.48},{#datetime(2025,4,15,0,0,0),"SE","direct_debit",172324,21106563.21,2284,120,20678.44,16431.05},{#datetime(2025,4,15,0,0,0),"SE","e_money",157983,13923715.97,1260,138,26703.54,17584.81},{#datetime(2025,4,15,0,0,0),"SE","cash_withdrawal",102716,9377198.03,679,57,8082.5,4670.75},{#datetime(2025,4,15,0,0,0),"NO","card",181597,9355590.48,1308,117,8430.56,4515.25},{#datetime(2025,4,15,0,0,0),"NO","credit_transfer",148755,17636076.07,1538,100,17414.78,10763.33},{#datetime(2025,4,15,0,0,0),"NO","direct_debit",193112,44211585.94,1188,210,93675.0,60026.18},{#datetime(2025,4,15,0,0,0),"NO","e_money",132211,12720759.86,1205,145,31898.82,21221.91},{#datetime(2025,4,15,0,0,0),"NO","cash_withdrawal",183165,36444884.97,2414,135,41764.46,26907.04},{#datetime(2025,4,15,0,0,0),"DK","card",141936,14748081.0,1622,94,13816.3,8800.38},{#datetime(2025,4,15,0,0,0),"DK","credit_transfer",73456,17339142.28,754,81,37655.87,26931.47},{#datetime(2025,4,15,0,0,0),"DK","direct_debit",62006,10340348.61,439,44,9284.78,5586.11},{#datetime(2025,4,15,0,0,0),"DK","e_money",95485,12242452.84,830,104,20824.45,17294.32},{#datetime(2025,4,15,0,0,0),"DK","cash_withdrawal",150510,13051574.59,1001,47,7748.78,6586.18},{#datetime(2025,4,15,0,0,0),"FI","card",131740,10666400.76,862,153,15513.59,7173.67},{#datetime(2025,4,15,0,0,0),"FI","credit_transfer",104823,7952809.89,646,45,4657.13,3342.81},{#datetime(2025,4,15,0,0,0),"FI","direct_debit",187841,43070098.5,1825,99,38125.64,26396.56},{#datetime(2025,4,15,0,0,0),"FI","e_money",70024,13615980.3,511,40,15184.7,12475.06},{#datetime(2025,4,15,0,0,0),"FI","cash_withdrawal",190941,33196275.5,2609,125,46278.76,22232.25},{#datetime(2025,4,15,0,0,0),"EE","card",103661,5793589.2,1262,110,12176.08,6068.83},{#datetime(2025,4,15,0,0,0),"EE","credit_transfer",188355,36812147.54,1653,129,42399.73,27660.92},{#datetime(2025,4,15,0,0,0),"EE","direct_debit",129451,4866540.87,1211,95,6298.45,3746.79},{#datetime(2025,4,15,0,0,0),"EE","e_money",160517,28892782.62,1522,154,68055.16,37977.02},{#datetime(2025,4,15,0,0,0),"EE","cash_withdrawal",181078,35093187.53,1759,188,71784.23,41557.46},{#datetime(2025,5,15,0,0,0),"SE","card",104355,21424066.77,698,114,35504.67,22576.83},{#datetime(2025,5,15,0,0,0),"SE","credit_transfer",199994,34394695.42,1738,148,41297.7,26637.84},{#datetime(2025,5,15,0,0,0),"SE","direct_debit",133015,26410877.54,1160,145,60792.4,34074.59},{#datetime(2025,5,15,0,0,0),"SE","e_money",42661,6011301.21,321,22,5357.89,3600.88},{#datetime(2025,5,15,0,0,0),"SE","cash_withdrawal",102999,18187039.63,1150,76,29936.82,14585.86},{#datetime(2025,5,15,0,0,0),"NO","card",98090,11565029.88,779,88,17427.83,11700.86},{#datetime(2025,5,15,0,0,0),"NO","credit_transfer",130113,15903488.4,1557,77,19893.36,11107.79},{#datetime(2025,5,15,0,0,0),"NO","direct_debit",105903,8711612.39,1246,61,10867.45,9023.8},{#datetime(2025,5,15,0,0,0),"NO","e_money",88535,6575131.41,1054,48,7009.97,5286.1},{#datetime(2025,5,15,0,0,0),"NO","cash_withdrawal",196445,18272279.45,1336,93,12938.6,6751.06},{#datetime(2025,5,15,0,0,0),"DK","card",43708,7873724.75,306,14,3205.19,1816.88},{#datetime(2025,5,15,0,0,0),"DK","credit_transfer",73103,12117793.01,878,28,5643.65,3181.53},{#datetime(2025,5,15,0,0,0),"DK","direct_debit",165492,20735502.78,1237,57,17307.5,11095.69},{#datetime(2025,5,15,0,0,0),"DK","e_money",57129,6692378.17,376,49,7288.17,3714.63},{#datetime(2025,5,15,0,0,0),"DK","cash_withdrawal",187545,43054847.56,1253,98,43319.66,26705.25},{#datetime(2025,5,15,0,0,0),"FI","card",196271,38685381.15,1531,151,53145.76,33327.09},{#datetime(2025,5,15,0,0,0),"FI","credit_transfer",194278,46229695.11,1640,166,78706.07,58717.54},{#datetime(2025,5,15,0,0,0),"FI","direct_debit",94470,15420393.01,766,35,8637.16,5793.78},{#datetime(2025,5,15,0,0,0),"FI","e_money",81034,2880639.02,778,67,3759.92,2040.1},{#datetime(2025,5,15,0,0,0),"FI","cash_withdrawal",114112,20438879.83,1099,104,44726.67,34221.77},{#datetime(2025,5,15,0,0,0),"EE","card",194609,33189110.01,2621,132,42950.61,30454.3},{#datetime(2025,5,15,0,0,0),"EE","credit_transfer",109633,22415496.05,720,49,16028.57,12014.75},{#datetime(2025,5,15,0,0,0),"EE","direct_debit",189214,42354507.25,1800,136,48566.04,29674.02},{#datetime(2025,5,15,0,0,0),"EE","e_money",111367,15323742.41,1108,41,7062.1,4398.36},{#datetime(2025,5,15,0,0,0),"EE","cash_withdrawal",124494,19764828.83,772,62,20440.27,16233.8},{#datetime(2025,6,15,0,0,0),"SE","card",193910,44582078.26,2714,175,62378.07,29073.96},{#datetime(2025,6,15,0,0,0),"SE","credit_transfer",85925,11295070.56,963,96,18120.73,12396.97},{#datetime(2025,6,15,0,0,0),"SE","direct_debit",168902,39465020.33,1648,112,42325.93,20817.58},{#datetime(2025,6,15,0,0,0),"SE","e_money",82159,8430314.54,948,45,11214.61,8696.1},{#datetime(2025,6,15,0,0,0),"SE","cash_withdrawal",184204,7832890.43,1234,97,5571.25,4228.69},{#datetime(2025,6,15,0,0,0),"NO","card",174898,35698444.19,1050,189,69460.21,32763.11},{#datetime(2025,6,15,0,0,0),"NO","credit_transfer",175905,19202628.63,2119,151,36066.53,19166.59},{#datetime(2025,6,15,0,0,0),"NO","direct_debit",183974,11380210.7,1527,201,22754.68,10502.37},{#datetime(2025,6,15,0,0,0),"NO","e_money",199612,39694705.65,2331,115,27849.12,17076.98},{#datetime(2025,6,15,0,0,0),"NO","cash_withdrawal",98903,23579732.61,1315,70,22575.16,17673.13},{#datetime(2025,6,15,0,0,0),"DK","card",170646,38599080.38,1422,159,62583.74,40241.33},{#datetime(2025,6,15,0,0,0),"DK","credit_transfer",163789,13916305.48,1705,105,21397.12,13978.66},{#datetime(2025,6,15,0,0,0),"DK","direct_debit",75784,16075720.53,622,76,28042.21,23098.35},{#datetime(2025,6,15,0,0,0),"DK","e_money",173100,15539255.54,1042,165,33900.77,23119.29},{#datetime(2025,6,15,0,0,0),"DK","cash_withdrawal",168356,35755181.6,1611,123,42636.49,32196.91},{#datetime(2025,6,15,0,0,0),"FI","card",138883,17825028.42,1190,65,17575.48,11928.81},{#datetime(2025,6,15,0,0,0),"FI","credit_transfer",101226,21306317.75,940,59,22537.91,18376.78},{#datetime(2025,6,15,0,0,0),"FI","direct_debit",139937,15973268.99,1582,145,40965.25,26550.87},{#datetime(2025,6,15,0,0,0),"FI","e_money",49704,3026003.64,682,29,2349.0,1851.05},{#datetime(2025,6,15,0,0,0),"FI","cash_withdrawal",66138,9445827.36,638,62,15345.19,10924.43},{#datetime(2025,6,15,0,0,0),"EE","card",80464,4050540.93,985,43,4351.38,2649.96},{#datetime(2025,6,15,0,0,0),"EE","credit_transfer",61054,12797644.02,782,65,23080.53,13309.72},{#datetime(2025,6,15,0,0,0),"EE","direct_debit",167912,35906053.33,1055,60,25923.76,21215.27},{#datetime(2025,6,15,0,0,0),"EE","e_money",99634,18739870.64,943,38,14465.24,11558.19},{#datetime(2025,6,15,0,0,0),"EE","cash_withdrawal",156307,10801561.05,1312,50,5603.32,2647.28}}), Typed = Table.TransformColumnTypes(Source,{{"kpi_date", type datetime},{"issuer_country", type text},{"instrument_type", type text},{"tx_count", Int64.Type},{"tx_value_eur", type number},{"decline_count", Int64.Type},{"fraud_count", Int64.Type},{"fraud_value_eur", type number},{"loss_value_eur", type number}}) in Typed

