table Fact_Eba
	lineageTag: fact-eba

	column Quarter
		dataType: string
		lineageTag: e1c01e7f-40b3-47a6-8afc-2f857d01996f
		summarizeBy: none
		sourceColumn: quarter

	column CountryCode
		dataType: string
		lineageTag: 86418a36-c69e-4157-a4f7-ca3e91e8c0d7
		summarizeBy: none
		sourceColumn: reporting_country

	column Instrument
		dataType: string
		lineageTag: f4bbdd59-1d44-4cfb-8596-db6429dbc6d2
		summarizeBy: none
		sourceColumn: instrument

	column Channel
		dataType: string
		lineageTag: 0a69fe38-a150-4b70-9ec1-fc2e156e004f
		summarizeBy: none
		sourceColumn: channel

	column ExemptionCode
		dataType: string
		lineageTag: 75f3b647-f4e7-4c10-91cc-b5fc0cdb5f89
		summarizeBy: none
		sourceColumn: sca_exemption

	column FraudTypeCode
		dataType: string
		lineageTag: 9b7a65ee-c9ca-4484-aabb-9b586587c58b
		summarizeBy: none
		sourceColumn: fraud_type

	column CounterpartyGeo
		dataType: string
		lineageTag: 4f522960-dc7f-4926-9216-c596d8269e95
		summarizeBy: none
		sourceColumn: counterparty_geo

	column LossBearer
		dataType: string
		lineageTag: 2aaf3ce7-fba9-4002-948f-08d251c1da04
		summarizeBy: none
		sourceColumn: loss_bearer

	column TxCount
		dataType: int64
		lineageTag: 352e8560-dea1-4037-aac4-e9197dca69e1
		summarizeBy: sum
		sourceColumn: tx_count

	column TxValueEur
		dataType: double
		formatString: "€"#,0.00
		lineageTag: ce4448cc-c651-49b5-82c5-1ff0778574cd
		summarizeBy: sum
		sourceColumn: tx_value_eur

	column FraudCount
		dataType: int64
		lineageTag: fa650ba6-5cf6-4ee1-9b15-d9ac9a4a8dd0
		summarizeBy: sum
		sourceColumn: fraud_count

	column FraudValueEur
		dataType: double
		formatString: "€"#,0.00
		lineageTag: 14e3b6d7-e3ff-486d-a7ff-6e6965461262
		summarizeBy: sum
		sourceColumn: fraud_value_eur

	column LossValueEur
		dataType: double
		formatString: "€"#,0.00
		lineageTag: f1ba1c4a-80b5-4d86-9d3f-9c6d0d890751
		summarizeBy: sum
		sourceColumn: loss_value_eur

	partition Fact_Eba = m
		mode: import
		source = let Source = #table({"quarter","reporting_country","instrument","channel","sca_exemption","fraud_type","counterparty_geo","loss_bearer","tx_count","tx_value_eur","fraud_count","fraud_value_eur","loss_value_eur"},{{"2025-Q3","SE","card","pos","tra","unauthorised_modification","domestic","merchant",662257,71173727.39,275,55658.92,38013.04},{"2025-Q3","SE","credit_transfer","moto","recurring","lost_stolen","eea","merchant",240450,36439745.08,118,41343.3,19495.8},{"2025-Q3","SE","direct_debit","ecommerce","mit","manipulation_of_payer","non_eea","payer",304287,61406162.2,204,66690.4,44902.58},{"2025-Q3","NO","card","moto","mit","unauthorised_issuance","domestic","payer",347990,74179369.47,296,113887.1,62758.72},{"2025-Q3","NO","credit_transfer","moto","recurring","unauthorised_issuance","non_eea","merchant",319882,33463661.34,172,37145.43,15265.65},{"2025-Q3","NO","direct_debit","pos","unattended","other","eea","psp",289140,58958821.09,259,116927.03,99559.56},{"2025-Q3","DK","card","pos","low_value","counterfeit","non_eea","psp",997673,74051061.65,499,78948.06,61874.39},{"2025-Q3","DK","credit_transfer","atm","corporate","counterfeit","eea","psp",366757,66731449.34,120,37054.32,17256.42},{"2025-Q3","DK","direct_debit","atm","tra","manipulation_of_payer","eea","payer",287384,18331844.52,210,31729.43,21113.6},{"2025-Q3","FI","card","pos","secure_corp","other","non_eea","payer",638443,117959951.19,430,109888.02,85391.32},{"2025-Q3","FI","credit_transfer","atm","unattended","lost_stolen","non_eea","payer",206282,37609957.11,64,21953.05,13773.19},{"2025-Q3","FI","direct_debit","atm","unattended","unauthorised_modification","non_eea","psp",219526,35447038.98,148,47481.2,41383.88},{"2025-Q3","EE","card","pos","sca_applied","unauthorised_issuance","eea","payer",996209,187580206.74,1023,314596.06,190062.56},{"2025-Q3","EE","credit_transfer","moto","unattended","counterfeit","non_eea","psp",128704,7399802.82,130,10798.64,6768.83},{"2025-Q3","EE","direct_debit","atm","sca_applied","counterfeit","eea","psp",444526,70184390.26,430,134172.74,116666.76},{"2025-Q4","SE","card","atm","contactless_lv","counterfeit","eea","psp",465444,55874343.56,227,46398.95,41316.59},{"2025-Q4","SE","credit_transfer","ecommerce","trusted","counterfeit","non_eea","merchant",895345,80275392.01,961,202029.62,164067.35},{"2025-Q4","SE","direct_debit","pos","low_value","other","non_eea","psp",255753,12558533.96,145,16988.96,13480.55},{"2025-Q4","NO","card","ecommerce","recurring","other","domestic","psp",1181557,93190881.5,1176,154094.02,73006.22},{"2025-Q4","NO","credit_transfer","ecommerce","corporate","other","domestic","merchant",1111361,94596570.79,487,84065.19,34709.68},{"2025-Q4","NO","direct_debit","ecommerce","low_value","lost_stolen","eea","payer",782272,33513002.24,400,24678.83,15065.93},{"2025-Q4","DK","card","atm","mit","counterfeit","domestic","psp",516718,75885189.19,342,77443.55,54795.45},{"2025-Q4","DK","credit_transfer","moto","low_value","unauthorised_issuance","eea","merchant",280899,54076954.93,180,49163.47,37177.45},{"2025-Q4","DK","direct_debit","atm","secure_corp","card_not_received","non_eea","payer",248877,12897519.04,129,13325.42,8983.71},{"2025-Q4","FI","card","pos","secure_corp","lost_stolen","domestic","payer",777118,101801863.93,500,142362.85,65089.3},{"2025-Q4","FI","credit_transfer","atm","recurring","manipulation_of_payer","domestic","merchant",388776,73453667.04,240,95379.9,53057.38},{"2025-Q4","FI","direct_debit","atm","tra","card_not_received","domestic","merchant",488113,25422901.32,471,34414.12,15427.24},{"2025-Q4","EE","card","moto","sca_applied","manipulation_of_payer","non_eea","payer",315546,44524546.42,264,65161.1,54527.04},{"2025-Q4","EE","credit_transfer","ecommerce","corporate","other","non_eea","payer",824654,48364400.59,581,50135.32,32141.48},{"2025-Q4","EE","direct_debit","ecommerce","unattended","counterfeit","non_eea","payer",464674,82372346.01,352,136660.56,112413.9},{"2026-Q1","SE","card","ecommerce","tra","other","domestic","merchant",334021,24208103.61,287,34121.94,19446.52},{"2026-Q1","SE","credit_transfer","pos","secure_corp","lost_stolen","eea","payer",1022666,114683001.98,422,94492.21,39245.31},{"2026-Q1","SE","direct_debit","ecommerce","sca_applied","unauthorised_modification","domestic","merchant",529330,56431609.97,464,106577.25,72877.17},{"2026-Q1","NO","card","moto","secure_corp","manipulation_of_payer","domestic","merchant",100872,16272038.4,52,17012.68,10936.28},{"2026-Q1","NO","credit_transfer","atm","sca_applied","unauthorised_modification","eea","merchant",223542,22830613.91,87,18138.1,12634.41},{"2026-Q1","NO","direct_debit","atm","recurring","manipulation_of_payer","domestic","psp",180210,7457756.29,97,6170.24,2891.48},{"2026-Q1","DK","card","atm","low_value","lost_stolen","non_eea","psp",505082,88117924.64,222,66518.18,50010.74},{"2026-Q1","DK","credit_transfer","moto","secure_corp","manipulation_of_payer","domestic","payer",262964,11405645.55,272,26563.77,18272.67},{"2026-Q1","DK","direct_debit","atm","low_value","lost_stolen","domestic","psp",155308,33222921.66,68,34022.76,21435.99},{"2026-Q1","FI","card","atm","trusted","manipulation_of_payer","domestic","psp",459787,67127489.14,330,83708.37,46469.64},{"2026-Q1","FI","credit_transfer","atm","tra","unauthorised_modification","domestic","psp",514696,79253116.57,372,86775.79,68389.22},{"2026-Q1","FI","direct_debit","pos","mit","lost_stolen","non_eea","merchant",538662,40673810.95,421,67893.25,49409.62},{"2026-Q1","EE","card","atm","corporate","unauthorised_modification","eea","psp",469498,76342216.27,472,153992.5,137556.27},{"2026-Q1","EE","credit_transfer","ecommerce","recurring","lost_stolen","eea","psp",1002964,119951884.52,544,104189.01,44601.87},{"2026-Q1","EE","direct_debit","ecommerce","unattended","card_not_received","non_eea","payer",376497,40049012.05,199,42454.9,37729},{"2026-Q2","SE","card","pos","corporate","card_not_received","eea","merchant",787966,113829040.42,837,255526.41,107451.76},{"2026-Q2","SE","credit_transfer","ecommerce","contactless_lv","counterfeit","domestic","psp",519374,110309867.25,342,159318.88,130432.55},{"2026-Q2","SE","direct_debit","atm","corporate","manipulation_of_payer","eea","payer",321845,53867744.38,351,110363.94,77795.84},{"2026-Q2","NO","card","atm","low_value","card_not_received","non_eea","payer",388362,62992950,132,42789.26,24275.4},{"2026-Q2","NO","credit_transfer","pos","corporate","unauthorised_issuance","non_eea","merchant",572641,48880231.17,561,113093.28,79318.02},{"2026-Q2","NO","direct_debit","pos","unattended","counterfeit","domestic","payer",400543,82117006.05,218,90561.56,66206.62},{"2026-Q2","DK","card","ecommerce","secure_corp","card_not_received","eea","psp",1139804,122873507.47,1063,251441.02,184823.79},{"2026-Q2","DK","credit_transfer","pos","trusted","unauthorised_modification","domestic","psp",667243,63785656.72,707,113308.3,88729.25},{"2026-Q2","DK","direct_debit","ecommerce","corporate","other","non_eea","psp",739732,142026406.15,281,116008.83,94844.17},{"2026-Q2","FI","card","pos","mit","unauthorised_issuance","eea","payer",950197,102440304.05,408,97466.47,76564.68},{"2026-Q2","FI","credit_transfer","pos","contactless_lv","unauthorised_modification","eea","payer",516428,110787249.49,407,185813.42,147145.69},{"2026-Q2","FI","direct_debit","atm","secure_corp","card_not_received","non_eea","payer",282408,29994941.28,298,75471.25,47610.28},{"2026-Q2","EE","card","moto","corporate","card_not_received","domestic","merchant",147972,27676745.49,139,37810.52,19850.58},{"2026-Q2","EE","credit_transfer","pos","secure_corp","unauthorised_issuance","domestic","payer",852115,164637140.88,450,185866.76,99698.12},{"2026-Q2","EE","direct_debit","moto","low_value","manipulation_of_payer","domestic","psp",226626,47021566.57,143,51582.72,30278.06}}), Typed = Table.TransformColumnTypes(Source,{{"quarter", type text},{"reporting_country", type text},{"instrument", type text},{"channel", type text},{"sca_exemption", type text},{"fraud_type", type text},{"counterparty_geo", type text},{"loss_bearer", type text},{"tx_count", Int64.Type},{"tx_value_eur", type number},{"fraud_count", Int64.Type},{"fraud_value_eur", type number},{"loss_value_eur", type number}}) in Typed

