table Fact_Exemption
	lineageTag: c6628d50-ca5c-4e18-a48c-53a0e5fb8b66

	column KpiDate
		dataType: dateTime
		lineageTag: 0072601a-ca92-4f55-bd4b-e8fbd1071433
		summarizeBy: none
		sourceColumn: kpi_date

	column CountryCode
		dataType: string
		lineageTag: 190d53ed-407a-431c-86c8-b8ed15aeaf37
		summarizeBy: none
		sourceColumn: issuer_country

	column ExemptionCode
		dataType: string
		lineageTag: 4848e6d6-c82a-4a43-9700-7a8b5ef25e34
		summarizeBy: none
		sourceColumn: sca_exemption_code

	column TxCount
		dataType: int64
		lineageTag: a1fe9542-9db7-4bf0-ab3f-0db957e0b6ae
		summarizeBy: sum
		sourceColumn: tx_count

	column TxValueEur
		dataType: double
		lineageTag: c898ba51-286e-4b58-a7ee-51f86448205f
		summarizeBy: sum
		sourceColumn: tx_value_eur

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column FraudCount
		dataType: int64
		lineageTag: 9cbc2674-f0dd-40bd-a2b3-3c95aae8b640
		summarizeBy: sum
		sourceColumn: fraud_count

	column FraudRateBps
		dataType: double
		lineageTag: 63e97238-9324-4de4-8aaf-2712702b7b3c
		summarizeBy: average
		sourceColumn: fraud_rate_bps

	partition Fact_Exemption = m
		mode: import
		source = let Source = #table({"kpi_date","issuer_country","sca_exemption_code","tx_count","tx_value_eur","fraud_count","fraud_rate_bps"},{{#datetime(2025,1,15,0,0,0),"SE","sca_applied",51770,7335762.85,58,7.97},{#datetime(2025,1,15,0,0,0),"SE","low_value",113727,5404979.94,27,11.05},{#datetime(2025,1,15,0,0,0),"SE","tra",71925,8165547.33,25,8.61},{#datetime(2025,1,15,0,0,0),"SE","trusted",68799,7144211.37,82,0.72},{#datetime(2025,1,15,0,0,0),"SE","recurring",38266,4982063.75,30,8.86},{#datetime(2025,1,15,0,0,0),"SE","corporate",79176,6396674.26,83,3.23},{#datetime(2025,1,15,0,0,0),"SE","secure_corp",25970,927906.38,17,9.63},{#datetime(2025,1,15,0,0,0),"SE","mit",69914,2624351.9,78,6.25},{#datetime(2025,1,15,0,0,0),"SE","contactless_lv",80261,2566124.14,61,3.28},{#datetime(2025,1,15,0,0,0),"SE","unattended",28818,1871805.14,5,4.56},{#datetime(2025,1,15,0,0,0),"NO","sca_applied",84798,6782831.87,78,1.48},{#datetime(2025,1,15,0,0,0),"NO","low_value",57265,2183028.77,44,6.33},{#datetime(2025,1,15,0,0,0),"NO","tra",76535,7385492.36,48,5.91},{#datetime(2025,1,15,0,0,0),"NO","trusted",93318,7131898.94,56,9.09},{#datetime(2025,1,15,0,0,0),"NO","recurring",56805,7079175.54,32,8.93},{#datetime(2025,1,15,0,0,0),"NO","corporate",92346,3919133.22,77,9.2},{#datetime(2025,1,15,0,0,0),"NO","secure_corp",27486,970813.29,22,9.86},{#datetime(2025,1,15,0,0,0),"NO","mit",32949,4271707.33,31,11.78},{#datetime(2025,1,15,0,0,0),"NO","contactless_lv",72722,7694591.32,79,1.23},{#datetime(2025,1,15,0,0,0),"NO","unattended",111736,16004239.81,26,2.82},{#datetime(2025,1,15,0,0,0),"DK","sca_applied",113692,6132134.92,27,11.23},{#datetime(2025,1,15,0,0,0),"DK","low_value",77552,6032528.64,85,5.94},{#datetime(2025,1,15,0,0,0),"DK","tra",14799,1781724.28,6,4.61},{#datetime(2025,1,15,0,0,0),"DK","trusted",112346,4014851.04,103,3.64},{#datetime(2025,1,15,0,0,0),"DK","recurring",114771,8511681.44,135,9.05},{#datetime(2025,1,15,0,0,0),"DK","corporate",60678,4288987.74,24,8.46},{#datetime(2025,1,15,0,0,0),"DK","secure_corp",58148,8194056.6,44,9.71},{#datetime(2025,1,15,0,0,0),"DK","mit",105300,8522977.72,70,11.94},{#datetime(2025,1,15,0,0,0),"DK","contactless_lv",33652,3212316.53,18,1.42},{#datetime(2025,1,15,0,0,0),"DK","unattended",96628,6326891.64,66,8.75},{#datetime(2025,1,15,0,0,0),"FI","sca_applied",31842,3590878.92,18,0.99},{#datetime(2025,1,15,0,0,0),"FI","low_value",56210,5833596.22,38,7.85},{#datetime(2025,1,15,0,0,0),"FI","tra",113740,16349957.28,32,7.83},{#datetime(2025,1,15,0,0,0),"FI","trusted",57619,5276190.4,59,2.34},{#datetime(2025,1,15,0,0,0),"FI","recurring",14081,663687.32,12,9.49},{#datetime(2025,1,15,0,0,0),"FI","corporate",14561,657394.25,6,7.92},{#datetime(2025,1,15,0,0,0),"FI","secure_corp",57467,4364189.27,47,7.46},{#datetime(2025,1,15,0,0,0),"FI","mit",99006,8315584.06,60,5.61},{#datetime(2025,1,15,0,0,0),"FI","contactless_lv",20077,1985025.31,15,5.08},{#datetime(2025,1,15,0,0,0),"FI","unattended",95139,6035881.88,119,0.8},{#datetime(2025,1,15,0,0,0),"EE","sca_applied",34385,3090705.19,21,6.96},{#datetime(2025,1,15,0,0,0),"EE","low_value",44311,5450064.15,43,2.97},{#datetime(2025,1,15,0,0,0),"EE","tra",90199,5797019.85,108,6.15},{#datetime(2025,1,15,0,0,0),"EE","trusted",26074,1206897.93,7,2.49},{#datetime(2025,1,15,0,0,0),"EE","recurring",103502,8633447.84,30,8.34},{#datetime(2025,1,15,0,0,0),"EE","corporate",51889,5715094.67,50,6.82},{#datetime(2025,1,15,0,0,0),"EE","secure_corp",48058,6582014.16,54,8.69},{#datetime(2025,1,15,0,0,0),"EE","mit",101779,10841906.47,109,6.35},{#datetime(2025,1,15,0,0,0),"EE","contactless_lv",25907,3839829.47,27,3.22},{#datetime(2025,1,15,0,0,0),"EE","unattended",74752,2478334.03,60,4.74},{#datetime(2025,2,15,0,0,0),"SE","sca_applied",115337,17065428.02,39,10.67},{#datetime(2025,2,15,0,0,0),"SE","low_value",18617,1249477.83,24,8.77},{#datetime(2025,2,15,0,0,0),"SE","tra",78903,6256646.09,51,7.11},{#datetime(2025,2,15,0,0,0),"SE","trusted",26426,3876312.81,23,5.67},{#datetime(2025,2,15,0,0,0),"SE","recurring",99143,9129404.84,33,10.03},{#datetime(2025,2,15,0,0,0),"SE","corporate",82260,8783333.84,32,11.61},{#datetime(2025,2,15,0,0,0),"SE","secure_corp",66704,6026283.12,77,10.06},{#datetime(2025,2,15,0,0,0),"SE","mit",77908,3767775.48,29,4.21},{#datetime(2025,2,15,0,0,0),"SE","contactless_lv",102973,5875272.2,127,6.47},{#datetime(2025,2,15,0,0,0),"SE","unattended",47230,6211313.87,22,7.8},{#datetime(2025,2,15,0,0,0),"NO","sca_applied",82199,5173122.06,72,7.57},{#datetime(2025,2,15,0,0,0),"NO","low_value",22245,2008918.75,8,11.33},{#datetime(2025,2,15,0,0,0),"NO","tra",30210,1526936.5,26,10.87},{#datetime(2025,2,15,0,0,0),"NO","trusted",54252,7112632.53,44,9.99},{#datetime(2025,2,15,0,0,0),"NO","recurring",13718,545245.81,17,9.37},{#datetime(2025,2,15,0,0,0),"NO","corporate",44688,4832363.57,46,5.29},{#datetime(2025,2,15,0,0,0),"NO","secure_corp",93753,3153317.26,110,6.77},{#datetime(2025,2,15,0,0,0),"NO","mit",94136,13630706.45,68,9.75},{#datetime(2025,2,15,0,0,0),"NO","contactless_lv",99783,7856025.67,69,8.42},{#datetime(2025,2,15,0,0,0),"NO","unattended",30719,2542078.96,22,2.85},{#datetime(2025,2,15,0,0,0),"DK","sca_applied",89516,4228757.59,102,4.17},{#datetime(2025,2,15,0,0,0),"DK","low_value",55268,8126877.28,19,4.76},{#datetime(2025,2,15,0,0,0),"DK","tra",83616,3573921.1,38,1.91},{#datetime(2025,2,15,0,0,0),"DK","trusted",68929,4118526.08,21,3.84},{#datetime(2025,2,15,0,0,0),"DK","recurring",60351,8068908.3,39,11.57},{#datetime(2025,2,15,0,0,0),"DK","corporate",30932,3947459.61,37,8.79},{#datetime(2025,2,15,0,0,0),"DK","secure_corp",34881,4240642.4,26,6.42},{#datetime(2025,2,15,0,0,0),"DK","mit",75373,10212218.4,56,1.54},{#datetime(2025,2,15,0,0,0),"DK","contactless_lv",61543,5579078.23,77,2.97},{#datetime(2025,2,15,0,0,0),"DK","unattended",56254,2016085.75,28,7.37},{#datetime(2025,2,15,0,0,0),"FI","sca_applied",95755,10600315.25,49,0.59},{#datetime(2025,2,15,0,0,0),"FI","low_value",24089,1968344.28,28,8.87},{#datetime(2025,2,15,0,0,0),"FI","tra",110120,8632360.61,27,1.09},{#datetime(2025,2,15,0,0,0),"FI","trusted",83638,4462809.62,67,1.35},{#datetime(2025,2,15,0,0,0),"FI","recurring",76093,6395047.91,61,9.99},{#datetime(2025,2,15,0,0,0),"FI","corporate",91689,10236878.51,30,11.71},{#datetime(2025,2,15,0,0,0),"FI","secure_corp",61629,4608850.83,79,6.92},{#datetime(2025,2,15,0,0,0),"FI","mit",57920,6984909.93,24,6.35},{#datetime(2025,2,15,0,0,0),"FI","contactless_lv",75546,2631311.66,18,8.71},{#datetime(2025,2,15,0,0,0),"FI","unattended",115377,10020411.46,81,7.47},{#datetime(2025,2,15,0,0,0),"EE","sca_applied",77568,3628143.78,94,4.16},{#datetime(2025,2,15,0,0,0),"EE","low_value",61505,9156488.51,62,3.94},{#datetime(2025,2,15,0,0,0),"EE","tra",54089,4915489.23,41,6.13},{#datetime(2025,2,15,0,0,0),"EE","trusted",83783,5527572.35,91,4.74},{#datetime(2025,2,15,0,0,0),"EE","recurring",98317,4242629.33,64,4.04},{#datetime(2025,2,15,0,0,0),"EE","corporate",105069,14147739.82,93,7.36},{#datetime(2025,2,15,0,0,0),"EE","secure_corp",44803,6543410.21,47,9.43},{#datetime(2025,2,15,0,0,0),"EE","mit",85711,4911684.89,21,6.03},{#datetime(2025,2,15,0,0,0),"EE","contactless_lv",78712,8302780.17,69,10.17},{#datetime(2025,2,15,0,0,0),"EE","unattended",29369,3776834.46,13,7.08},{#datetime(2025,3,15,0,0,0),"SE","sca_applied",101818,4397261.06,22,4.11},{#datetime(2025,3,15,0,0,0),"SE","low_value",29848,2374564.0,12,6.27},{#datetime(2025,3,15,0,0,0),"SE","tra",90147,12662274.25,104,8.96},{#datetime(2025,3,15,0,0,0),"SE","trusted",18163,2083169.46,13,6.95},{#datetime(2025,3,15,0,0,0),"SE","recurring",96799,8460669.94,59,11.5},{#datetime(2025,3,15,0,0,0),"SE","corporate",70249,9796567.22,40,4.57},{#datetime(2025,3,15,0,0,0),"SE","secure_corp",111186,14912102.7,105,9.74},{#datetime(2025,3,15,0,0,0),"SE","mit",44650,4608290.32,18,3.33},{#datetime(2025,3,15,0,0,0),"SE","contactless_lv",83149,5472858.81,102,11.8},{#datetime(2025,3,15,0,0,0),"SE","unattended",111079,7184644.87,47,8.61},{#datetime(2025,3,15,0,0,0),"NO","sca_applied",51555,4515001.86,42,11.25},{#datetime(2025,3,15,0,0,0),"NO","low_value",104589,6569748.04,34,8.28},{#datetime(2025,3,15,0,0,0),"NO","tra",59767,8217439.86,37,4.47},{#datetime(2025,3,15,0,0,0),"NO","trusted",111327,14088866.03,57,3.81},{#datetime(2025,3,15,0,0,0),"NO","recurring",103603,4090612.4,126,8.04},{#datetime(2025,3,15,0,0,0),"NO","corporate",107955,9444930.22,45,6.69},{#datetime(2025,3,15,0,0,0),"NO","secure_corp",83664,9499257.08,29,7.58},{#datetime(2025,3,15,0,0,0),"NO","mit",86917,5103231.52,22,10.91},{#datetime(2025,3,15,0,0,0),"NO","contactless_lv",39579,4217274.99,10,5.25},{#datetime(2025,3,15,0,0,0),"NO","unattended",104025,9017767.97,98,2.08},{#datetime(2025,3,15,0,0,0),"DK","sca_applied",82135,12102533.56,30,8.01},{#datetime(2025,3,15,0,0,0),"DK","low_value",72350,6315708.05,30,11.59},{#datetime(2025,3,15,0,0,0),"DK","tra",52096,3347159.71,13,9.34},{#datetime(2025,3,15,0,0,0),"DK","trusted",95498,9444370.44,75,8.82},{#datetime(2025,3,15,0,0,0),"DK","recurring",14888,2078179.7,5,10.65},{#datetime(2025,3,15,0,0,0),"DK","corporate",33040,4694016.37,7,10.12},{#datetime(2025,3,15,0,0,0),"DK","secure_corp",113279,10132361.1,139,11.56},{#datetime(2025,3,15,0,0,0),"DK","mit",47941,6482063.31,10,7.03},{#datetime(2025,3,15,0,0,0),"DK","contactless_lv",24064,3403000.49,13,5.73},{#datetime(2025,3,15,0,0,0),"DK","unattended",94058,8953950.83,69,11.29},{#datetime(2025,3,15,0,0,0),"FI","sca_applied",76088,6555931.71,31,1.8},{#datetime(2025,3,15,0,0,0),"FI","low_value",31298,3684848.37,28,8.76},{#datetime(2025,3,15,0,0,0),"FI","tra",11846,1402497.07,12,7.03},{#datetime(2025,3,15,0,0,0),"FI","trusted",109258,5810269.92,95,7.85},{#datetime(2025,3,15,0,0,0),"FI","recurring",63148,8161170.42,48,1.5},{#datetime(2025,3,15,0,0,0),"FI","corporate",97720,4050123.9,125,5.99},{#datetime(2025,3,15,0,0,0),"FI","secure_corp",42512,1310203.45,26,5.64},{#datetime(2025,3,15,0,0,0),"FI","mit",44995,6501065.62,23,8.81},{#datetime(2025,3,15,0,0,0),"FI","contactless_lv",11498,705820.58,6,3.22},{#datetime(2025,3,15,0,0,0),"FI","unattended",97528,4309467.95,52,5.16},{#datetime(2025,3,15,0,0,0),"EE","sca_applied",75866,10679863.3,89,9.35},{#datetime(2025,3,15,0,0,0),"EE","low_value",100477,4430019.83,121,3.89},{#datetime(2025,3,15,0,0,0),"EE","tra",90560,5116812.86,113,6.0},{#datetime(2025,3,15,0,0,0),"EE","trusted",69634,8337152.12,60,5.28},{#datetime(2025,3,15,0,0,0),"EE","recurring",81989,11440386.49,84,9.72},{#datetime(2025,3,15,0,0,0),"EE","corporate",118213,6644681.18,55,9.18},{#datetime(2025,3,15,0,0,0),"EE","secure_corp",113202,4508205.89,78,8.59},{#datetime(2025,3,15,0,0,0),"EE","mit",20237,2834583.74,6,10.03},{#datetime(2025,3,15,0,0,0),"EE","contactless_lv",76255,4137505.82,60,2.39},{#datetime(2025,3,15,0,0,0),"EE","unattended",78202,6492397.79,74,8.74},{#datetime(2025,4,15,0,0,0),"SE","sca_applied",74071,3030466.63,56,9.8},{#datetime(2025,4,15,0,0,0),"SE","low_value",69432,3182299.13,45,6.98},{#datetime(2025,4,15,0,0,0),"SE","tra",83242,7115975.39,90,8.82},{#datetime(2025,4,15,0,0,0),"SE","trusted",61897,3746926.62,12,3.01},{#datetime(2025,4,15,0,0,0),"SE","recurring",19572,693529.44,11,1.23},{#datetime(2025,4,15,0,0,0),"SE","corporate",17897,2544057.4,4,11.24},{#datetime(2025,4,15,0,0,0),"SE","secure_corp",14159,912560.08,5,2.06},{#datetime(2025,4,15,0,0,0),"SE","mit",94085,13868128.45,85,5.33},{#datetime(2025,4,15,0,0,0),"SE","contactless_lv",60132,5040532.18,72,4.84},{#datetime(2025,4,15,0,0,0),"SE","unattended",20518,2296531.37,19,6.7},{#datetime(2025,4,15,0,0,0),"NO","sca_applied",95660,12745201.72,31,11.92},{#datetime(2025,4,15,0,0,0),"NO","low_value",61518,5749540.24,61,3.06},{#datetime(2025,4,15,0,0,0),"NO","tra",10455,1262352.69,13,5.82},{#datetime(2025,4,15,0,0,0),"NO","trusted",104253,9938797.19,81,9.97},{#datetime(2025,4,15,0,0,0),"NO","recurring",42441,3619157.69,15,2.67},{#datetime(2025,4,15,0,0,0),"NO","corporate",105030,12798828.87,24,8.09},{#datetime(2025,4,15,0,0,0),"NO","secure_corp",90599,11046411.37,106,0.68},{#datetime(2025,4,15,0,0,0),"NO","mit",37011,1409190.43,31,5.63},{#datetime(2025,4,15,0,0,0),"NO","contactless_lv",98083,11220141.23,24,9.02},{#datetime(2025,4,15,0,0,0),"NO","unattended",62725,5185823.08,49,9.18},{#datetime(2025,4,15,0,0,0),"DK","sca_applied",111720,4108311.31,84,3.83},{#datetime(2025,4,15,0,0,0),"DK","low_value",116926,16365856.74,97,7.14},{#datetime(2025,4,15,0,0,0),"DK","tra",111258,12316686.51,61,3.97},{#datetime(2025,4,15,0,0,0),"DK","trusted",28777,4267153.34,22,5.26},{#datetime(2025,4,15,0,0,0),"DK","recurring",46064,1718874.31,57,10.62},{#datetime(2025,4,15,0,0,0),"DK","corporate",32955,3464202.46,22,6.2},{#datetime(2025,4,15,0,0,0),"DK","secure_corp",55143,7884917.93,51,9.54},{#datetime(2025,4,15,0,0,0),"DK","mit",51777,5879641.25,33,3.95},{#datetime(2025,4,15,0,0,0),"DK","contactless_lv",34101,4110191.2,24,10.27},{#datetime(2025,4,15,0,0,0),"DK","unattended",49418,6567896.75,17,5.82},{#datetime(2025,4,15,0,0,0),"FI","sca_applied",17552,1711079.78,22,6.91},{#datetime(2025,4,15,0,0,0),"FI","low_value",27575,2112528.63,13,4.3},{#datetime(2025,4,15,0,0,0),"FI","tra",20363,2864404.82,23,1.56},{#datetime(2025,4,15,0,0,0),"FI","trusted",104972,13596892.39,26,4.84},{#datetime(2025,4,15,0,0,0),"FI","recurring",89294,9139298.53,103,2.66},{#datetime(2025,4,15,0,0,0),"FI","corporate",109837,11039721.56,103,3.0},{#datetime(2025,4,15,0,0,0),"FI","secure_corp",37379,5021377.57,21,11.51},{#datetime(2025,4,15,0,0,0),"FI","mit",12009,665501.94,4,9.03},{#datetime(2025,4,15,0,0,0),"FI","contactless_lv",107894,16178558.66,78,3.29},{#datetime(2025,4,15,0,0,0),"FI","unattended",89220,10211427.95,56,3.25},{#datetime(2025,4,15,0,0,0),"EE","sca_applied",52154,6418158.12,32,6.64},{#datetime(2025,4,15,0,0,0),"EE","low_value",57088,3825505.36,34,10.65},{#datetime(2025,4,15,0,0,0),"EE","tra",71080,2973488.77,90,5.9},{#datetime(2025,4,15,0,0,0),"EE","trusted",51973,7261649.88,31,5.26},{#datetime(2025,4,15,0,0,0),"EE","recurring",83731,11194012.54,85,0.69},{#datetime(2025,4,15,0,0,0),"EE","corporate",82523,11732376.61,69,5.3},{#datetime(2025,4,15,0,0,0),"EE","secure_corp",29976,1605005.39,13,7.05},{#datetime(2025,4,15,0,0,0),"EE","mit",42208,3795182.04,38,8.38},{#datetime(2025,4,15,0,0,0),"EE","contactless_lv",43728,5317468.01,32,8.82},{#datetime(2025,4,15,0,0,0),"EE","unattended",106940,9503914.99,41,9.64},{#datetime(2025,5,15,0,0,0),"SE","sca_applied",32185,1506097.83,25,2.62},{#datetime(2025,5,15,0,0,0),"SE","low_value",81058,12064577.47,101,6.53},{#datetime(2025,5,15,0,0,0),"SE","tra",119978,15789547.04,148,8.18},{#datetime(2025,5,15,0,0,0),"SE","trusted",110183,3389896.67,38,7.75},{#datetime(2025,5,15,0,0,0),"SE","recurring",18908,2171779.45,3,6.32},{#datetime(2025,5,15,0,0,0),"SE","corporate",58916,2194857.5,53,11.24},{#datetime(2025,5,15,0,0,0),"SE","secure_corp",73334,8001774.95,15,6.62},{#datetime(2025,5,15,0,0,0),"SE","mit",63914,2008313.13,50,3.66},{#datetime(2025,5,15,0,0,0),"SE","contactless_lv",47576,1525149.15,52,8.25},{#datetime(2025,5,15,0,0,0),"SE","unattended",115666,16513106.17,45,11.06},{#datetime(2025,5,15,0,0,0),"NO","sca_applied",78732,3768719.62,32,6.55},{#datetime(2025,5,15,0,0,0),"NO","low_value",116851,8475545.65,125,1.41},{#datetime(2025,5,15,0,0,0),"NO","tra",63218,5378570.34,29,8.52},{#datetime(2025,5,15,0,0,0),"NO","trusted",49318,5527807.79,55,8.02},{#datetime(2025,5,15,0,0,0),"NO","recurring",95182,11531328.05,28,4.86},{#datetime(2025,5,15,0,0,0),"NO","corporate",82443,7182484.62,74,8.58},{#datetime(2025,5,15,0,0,0),"NO","secure_corp",20837,1874975.92,14,9.52},{#datetime(2025,5,15,0,0,0),"NO","mit",84167,12396074.25,106,10.79},{#datetime(2025,5,15,0,0,0),"NO","contactless_lv",15577,896798.73,18,8.46},{#datetime(2025,5,15,0,0,0),"NO","unattended",84289,7338203.25,21,1.36},{#datetime(2025,5,15,0,0,0),"DK","sca_applied",46749,6447500.44,38,0.88},{#datetime(2025,5,15,0,0,0),"DK","low_value",51220,1632840.92,21,2.16},{#datetime(2025,5,15,0,0,0),"DK","tra",117569,13582201.99,75,1.38},{#datetime(2025,5,15,0,0,0),"DK","trusted",31292,3056445.6,25,10.27},{#datetime(2025,5,15,0,0,0),"DK","recurring",98740,13584954.51,55,9.19},{#datetime(2025,5,15,0,0,0),"DK","corporate",28343,3538900.47,27,1.4},{#datetime(2025,5,15,0,0,0),"DK","secure_corp",107708,15824330.03,27,5.53},{#datetime(2025,5,15,0,0,0),"DK","mit",119926,4691767.71,103,7.56},{#datetime(2025,5,15,0,0,0),"DK","contactless_lv",88067,6834383.69,92,0.84},{#datetime(2025,5,15,0,0,0),"DK","unattended",45825,5683481.22,31,3.12},{#datetime(2025,5,15,0,0,0),"FI","sca_applied",82487,11790455.98,55,8.32},{#datetime(2025,5,15,0,0,0),"FI","low_value",96595,7303424.85,101,3.9},{#datetime(2025,5,15,0,0,0),"FI","tra",42302,4888970.06,12,2.27},{#datetime(2025,5,15,0,0,0),"FI","trusted",103280,12813622.6,38,4.98},{#datetime(2025,5,15,0,0,0),"FI","recurring",57277,2450660.03,11,4.05},{#datetime(2025,5,15,0,0,0),"FI","corporate",57175,6938848.28,17,1.5},{#datetime(2025,5,15,0,0,0),"FI","secure_corp",66489,5575850.07,53,5.19},{#datetime(2025,5,15,0,0,0),"FI","mit",13442,547818.78,10,7.36},{#datetime(2025,5,15,0,0,0),"FI","contactless_lv",112817,7776660.79,70,3.86},{#datetime(2025,5,15,0,0,0),"FI","unattended",60829,7512399.3,60,6.93},{#datetime(2025,5,15,0,0,0),"EE","sca_applied",41816,4124531.68,16,4.88},{#datetime(2025,5,15,0,0,0),"EE","low_value",28198,1755897.23,13,2.18},{#datetime(2025,5,15,0,0,0),"EE","tra",31916,2622255.34,21,6.07},{#datetime(2025,5,15,0,0,0),"EE","trusted",20082,1472713.26,24,8.79},{#datetime(2025,5,15,0,0,0),"EE","recurring",74985,7592738.73,31,1.73},{#datetime(2025,5,15,0,0,0),"EE","corporate",49932,1538508.99,31,10.18},{#datetime(2025,5,15,0,0,0),"EE","secure_corp",59792,7563040.78,33,4.35},{#datetime(2025,5,15,0,0,0),"EE","mit",116886,15057748.81,107,7.34},{#datetime(2025,5,15,0,0,0),"EE","contactless_lv",49378,3381396.49,61,2.81},{#datetime(2025,5,15,0,0,0),"EE","unattended",51180,2626377.07,32,4.17},{#datetime(2025,6,15,0,0,0),"SE","sca_applied",106321,12056262.58,78,7.12},{#datetime(2025,6,15,0,0,0),"SE","low_value",41775,2886917.71,21,9.54},{#datetime(2025,6,15,0,0,0),"SE","tra",57843,2525803.61,47,7.31},{#datetime(2025,6,15,0,0,0),"SE","trusted",81516,4205513.6,85,0.81},{#datetime(2025,6,15,0,0,0),"SE","recurring",105317,8993510.12,103,5.54},{#datetime(2025,6,15,0,0,0),"SE","corporate",48185,6252187.67,13,10.25},{#datetime(2025,6,15,0,0,0),"SE","secure_corp",114208,9033509.13,85,7.78},{#datetime(2025,6,15,0,0,0),"SE","mit",41722,2516746.23,15,5.37},{#datetime(2025,6,15,0,0,0),"SE","contactless_lv",59412,2309690.0,76,6.01},{#datetime(2025,6,15,0,0,0),"SE","unattended",62534,5885955.73,76,10.5},{#datetime(2025,6,15,0,0,0),"NO","sca_applied",64827,6173956.51,69,4.63},{#datetime(2025,6,15,0,0,0),"NO","low_value",116469,10998018.39,105,1.48},{#datetime(2025,6,15,0,0,0),"NO","tra",110788,6623761.51,103,2.41},{#datetime(2025,6,15,0,0,0),"NO","trusted",90304,3189140.23,115,8.29},{#datetime(2025,6,15,0,0,0),"NO","recurring",62378,9108269.39,35,9.66},{#datetime(2025,6,15,0,0,0),"NO","corporate",23886,746813.29,11,6.37},{#datetime(2025,6,15,0,0,0),"NO","secure_corp",77999,7562721.42,74,3.04},{#datetime(2025,6,15,0,0,0),"NO","mit",59036,4541999.61,61,7.27},{#datetime(2025,6,15,0,0,0),"NO","contactless_lv",75597,3635413.76,98,6.05},{#datetime(2025,6,15,0,0,0),"NO","unattended",48722,3893718.58,61,1.83},{#datetime(2025,6,15,0,0,0),"DK","sca_applied",105702,4968101.94,57,5.74},{#datetime(2025,6,15,0,0,0),"DK","low_value",37114,3434298.7,21,1.62},{#datetime(2025,6,15,0,0,0),"DK","tra",104633,11887521.69,57,3.95},{#datetime(2025,6,15,0,0,0),"DK","trusted",116192,13396179.89,26,4.45},{#datetime(2025,6,15,0,0,0),"DK","recurring",24334,2707321.02,9,11.81},{#datetime(2025,6,15,0,0,0),"DK","corporate",41970,3857851.69,33,4.31},{#datetime(2025,6,15,0,0,0),"DK","secure_corp",65885,9554347.18,29,5.16},{#datetime(2025,6,15,0,0,0),"DK","mit",34176,1789675.15,31,5.05},{#datetime(2025,6,15,0,0,0),"DK","contactless_lv",106650,11058840.58,44,7.31},{#datetime(2025,6,15,0,0,0),"DK","unattended",60965,1861505.63,26,3.7},{#datetime(2025,6,15,0,0,0),"FI","sca_applied",102243,12989725.17,27,1.67},{#datetime(2025,6,15,0,0,0),"FI","low_value",80371,4214267.87,44,5.76},{#datetime(2025,6,15,0,0,0),"FI","tra",44387,4904060.92,32,11.61},{#datetime(2025,6,15,0,0,0),"FI","trusted",51078,5191389.12,44,7.25},{#datetime(2025,6,15,0,0,0),"FI","recurring",55603,4016660.13,39,2.48},{#datetime(2025,6,15,0,0,0),"FI","corporate",98288,11275462.08,51,7.57},{#datetime(2025,6,15,0,0,0),"FI","secure_corp",21108,2335667.95,11,3.24},{#datetime(2025,6,15,0,0,0),"FI","mit",25328,1316178.19,24,6.37},{#datetime(2025,6,15,0,0,0),"FI","contactless_lv",64819,6583737.01,53,5.36},{#datetime(2025,6,15,0,0,0),"FI","unattended",73788,7840727.42,71,7.92},{#datetime(2025,6,15,0,0,0),"EE","sca_applied",32706,3159056.48,24,2.11},{#datetime(2025,6,15,0,0,0),"EE","low_value",51232,6713350.38,45,10.45},{#datetime(2025,6,15,0,0,0),"EE","tra",11256,992250.96,4,4.92},{#datetime(2025,6,15,0,0,0),"EE","trusted",83607,7579188.78,62,8.37},{#datetime(2025,6,15,0,0,0),"EE","recurring",64477,7428851.97,44,2.42},{#datetime(2025,6,15,0,0,0),"EE","corporate",84107,2834682.16,87,3.86},{#datetime(2025,6,15,0,0,0),"EE","secure_corp",46025,2622560.19,23,9.48},{#datetime(2025,6,15,0,0,0),"EE","mit",84140,10021258.29,87,6.82},{#datetime(2025,6,15,0,0,0),"EE","contactless_lv",24838,2452148.6,12,6.75},{#datetime(2025,6,15,0,0,0),"EE","unattended",58085,5520700.76,59,9.24}}), Typed = Table.TransformColumnTypes(Source,{{"kpi_date", type datetime},{"issuer_country", type text},{"sca_exemption_code", type text},{"tx_count", Int64.Type},{"tx_value_eur", type number},{"fraud_count", Int64.Type},{"fraud_rate_bps", type number}}) in Typed

