table Fact_Exemption
	lineageTag: c6628d50-ca5c-4e18-a48c-53a0e5fb8b66

	column KpiDate
		dataType: dateTime
		lineageTag: 0072601a-ca92-4f55-bd4b-e8fbd1071433
		summarizeBy: none
		sourceColumn: kpi_date

	column CountryCode
		dataType: string
		lineageTag: 190d53ed-407a-431c-86c8-b8ed15aeaf37
		summarizeBy: none
		sourceColumn: issuer_country

	column ExemptionCode
		dataType: string
		lineageTag: 4848e6d6-c82a-4a43-9700-7a8b5ef25e34
		summarizeBy: none
		sourceColumn: sca_exemption_code

	column TxCount
		dataType: int64
		lineageTag: a1fe9542-9db7-4bf0-ab3f-0db957e0b6ae
		summarizeBy: sum
		sourceColumn: tx_count

	column TxValueEur
		dataType: double
		lineageTag: c898ba51-286e-4b58-a7ee-51f86448205f
		summarizeBy: sum
		sourceColumn: tx_value_eur

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column FraudCount
		dataType: int64
		lineageTag: 9cbc2674-f0dd-40bd-a2b3-3c95aae8b640
		summarizeBy: sum
		sourceColumn: fraud_count

	column FraudRateBps
		dataType: double
		lineageTag: 63e97238-9324-4de4-8aaf-2712702b7b3c
		summarizeBy: average
		sourceColumn: fraud_rate_bps

	partition Fact_Exemption = m
		mode: import
		source = let Source = #table({"kpi_date","issuer_country","sca_exemption_code","tx_count","tx_value_eur","fraud_count","fraud_rate_bps"},{{#datetime(2026,1,15,0,0,0),"SE","sca_applied",127225,18027705.25,143,7.97},{#datetime(2026,1,15,0,0,0),"SE","low_value",168260,7996707.49,40,11.05},{#datetime(2026,1,15,0,0,0),"SE","tra",106930,12139612.65,37,8.61},{#datetime(2026,1,15,0,0,0),"SE","trusted",38291,3976168.74,46,0.72},{#datetime(2026,1,15,0,0,0),"SE","recurring",31188,4060478.84,24,8.86},{#datetime(2026,1,15,0,0,0),"SE","corporate",39764,3212525.98,42,3.23},{#datetime(2026,1,15,0,0,0),"SE","secure_corp",11210,400532.8,7,9.63},{#datetime(2026,1,15,0,0,0),"SE","mit",43829,1645194.53,49,6.25},{#datetime(2026,1,15,0,0,0),"SE","contactless_lv",103324,3303505.38,79,3.28},{#datetime(2026,1,15,0,0,0),"SE","unattended",8042,522370.94,1,4.56},{#datetime(2026,1,15,0,0,0),"NO","sca_applied",208392,16668872.24,192,1.48},{#datetime(2026,1,15,0,0,0),"NO","low_value",84724,3229807.09,65,6.33},{#datetime(2026,1,15,0,0,0),"NO","tra",113784,10979915.1,71,5.91},{#datetime(2026,1,15,0,0,0),"NO","trusted",51937,3969316.15,31,9.09},{#datetime(2026,1,15,0,0,0),"NO","recurring",46297,5769665.74,26,8.93},{#datetime(2026,1,15,0,0,0),"NO","corporate",46378,1968259.87,39,9.2},{#datetime(2026,1,15,0,0,0),"NO","secure_corp",11864,419053.67,9,9.86},{#datetime(2026,1,15,0,0,0),"NO","mit",20656,2677914.32,19,11.78},{#datetime(2026,1,15,0,0,0),"NO","contactless_lv",93619,9905648.53,102,1.23},{#datetime(2026,1,15,0,0,0),"NO","unattended",31183,4466356.92,7,2.82},{#datetime(2026,1,15,0,0,0),"DK","sca_applied",279399,15069778.45,66,11.23},{#datetime(2026,1,15,0,0,0),"DK","low_value",114739,8925170.4,126,5.94},{#datetime(2026,1,15,0,0,0),"DK","tra",22001,2648866.23,9,4.61},{#datetime(2026,1,15,0,0,0),"DK","trusted",62527,2234497.88,57,3.64},{#datetime(2026,1,15,0,0,0),"DK","recurring",93541,6937185.9,110,9.05},{#datetime(2026,1,15,0,0,0),"DK","corporate",30474,2154007.53,12,8.46},{#datetime(2026,1,15,0,0,0),"DK","secure_corp",25100,3536982.33,19,9.71},{#datetime(2026,1,15,0,0,0),"DK","mit",66012,5343016.8,44,11.94},{#datetime(2026,1,15,0,0,0),"DK","contactless_lv",43322,4135382.53,23,1.42},{#datetime(2026,1,15,0,0,0),"DK","unattended",26966,1765666.88,18,8.75},{#datetime(2026,1,15,0,0,0),"FI","sca_applied",78252,8824618.25,44,0.99},{#datetime(2026,1,15,0,0,0),"FI","low_value",83163,8630848.43,56,7.85},{#datetime(2026,1,15,0,0,0),"FI","tra",169096,24307268.11,48,7.83},{#datetime(2026,1,15,0,0,0),"FI","trusted",32068,2936506.53,33,2.34},{#datetime(2026,1,15,0,0,0),"FI","recurring",11476,540918.07,10,9.49},{#datetime(2026,1,15,0,0,0),"FI","corporate",7313,330155.33,3,7.92},{#datetime(2026,1,15,0,0,0),"FI","secure_corp",24806,1883811.78,20,7.46},{#datetime(2026,1,15,0,0,0),"FI","mit",62066,5213002.64,38,5.61},{#datetime(2026,1,15,0,0,0),"FI","contactless_lv",25846,2555426.56,19,5.08},{#datetime(2026,1,15,0,0,0),"FI","unattended",26551,1684453.81,33,0.8},{#datetime(2026,1,15,0,0,0),"EE","sca_applied",84501,7595436.67,52,6.96},{#datetime(2026,1,15,0,0,0),"EE","low_value",65558,8063409.91,64,2.97},{#datetime(2026,1,15,0,0,0),"EE","tra",134098,8618353.76,161,6.15},{#datetime(2026,1,15,0,0,0),"EE","trusted",14512,671708.82,4,2.49},{#datetime(2026,1,15,0,0,0),"EE","recurring",84356,7036427.89,24,8.34},{#datetime(2026,1,15,0,0,0),"EE","corporate",26060,2870224.33,25,6.82},{#datetime(2026,1,15,0,0,0),"EE","secure_corp",20744,2841140.71,23,8.69},{#datetime(2026,1,15,0,0,0),"EE","mit",63805,6796742.92,68,6.35},{#datetime(2026,1,15,0,0,0),"EE","contactless_lv",33351,4943212.65,35,3.22},{#datetime(2026,1,15,0,0,0),"EE","unattended",20861,691637,17,4.74},{#datetime(2026,2,15,0,0,0),"SE","sca_applied",283442,41938447.65,96,10.67},{#datetime(2026,2,15,0,0,0),"SE","low_value",27544,1848611.62,36,8.77},{#datetime(2026,2,15,0,0,0),"SE","tra",117304,9301674.09,76,7.11},{#datetime(2026,2,15,0,0,0),"SE","trusted",14708,2157393.31,13,5.67},{#datetime(2026,2,15,0,0,0),"SE","recurring",80803,7440642.49,27,10.03},{#datetime(2026,2,15,0,0,0),"SE","corporate",41312,4411149.76,16,11.61},{#datetime(2026,2,15,0,0,0),"SE","secure_corp",28793,2601258.2,33,10.06},{#datetime(2026,2,15,0,0,0),"SE","mit",48840,2362001.68,18,4.21},{#datetime(2026,2,15,0,0,0),"SE","contactless_lv",132563,7563544.18,163,6.47},{#datetime(2026,2,15,0,0,0),"SE","unattended",13181,1733412.21,6,7.8},{#datetime(2026,2,15,0,0,0),"NO","sca_applied",202005,12712995.45,177,7.57},{#datetime(2026,2,15,0,0,0),"NO","low_value",32912,2972210.04,12,11.33},{#datetime(2026,2,15,0,0,0),"NO","tra",44913,2270076.57,39,10.87},{#datetime(2026,2,15,0,0,0),"NO","trusted",30194,3958593.28,24,9.99},{#datetime(2026,2,15,0,0,0),"NO","recurring",11180,444385.94,14,9.37},{#datetime(2026,2,15,0,0,0),"NO","corporate",22443,2426900.74,23,5.29},{#datetime(2026,2,15,0,0,0),"NO","secure_corp",40469,1361136.25,47,6.77},{#datetime(2026,2,15,0,0,0),"NO","mit",59013,8545029.21,43,9.75},{#datetime(2026,2,15,0,0,0),"NO","contactless_lv",128456,10113471.38,89,8.42},{#datetime(2026,2,15,0,0,0),"NO","unattended",8573,709426.51,6,2.85},{#datetime(2026,2,15,0,0,0),"DK","sca_applied",219986,10392211,251,4.17},{#datetime(2026,2,15,0,0,0),"DK","low_value",81769,12023774.59,28,4.76},{#datetime(2026,2,15,0,0,0),"DK","tra",124311,5313301.86,56,1.91},{#datetime(2026,2,15,0,0,0),"DK","trusted",38363,2292199.07,12,3.84},{#datetime(2026,2,15,0,0,0),"DK","recurring",49187,6576317.18,32,11.57},{#datetime(2026,2,15,0,0,0),"DK","corporate",15535,1982485.9,19,8.79},{#datetime(2026,2,15,0,0,0),"DK","secure_corp",15056,1830482.5,11,6.42},{#datetime(2026,2,15,0,0,0),"DK","mit",47251,6401994.27,35,1.54},{#datetime(2026,2,15,0,0,0),"DK","contactless_lv",79228,7182238.25,99,2.97},{#datetime(2026,2,15,0,0,0),"DK","unattended",15699,562635.82,8,7.37},{#datetime(2026,2,15,0,0,0),"FI","sca_applied",235319,26050373.05,120,0.59},{#datetime(2026,2,15,0,0,0),"FI","low_value",35640,2912179.81,41,8.87},{#datetime(2026,2,15,0,0,0),"FI","tra",163714,12833617.86,40,1.09},{#datetime(2026,2,15,0,0,0),"FI","trusted",46549,2483812.86,37,1.35},{#datetime(2026,2,15,0,0,0),"FI","recurring",62017,5212088.41,50,9.99},{#datetime(2026,2,15,0,0,0),"FI","corporate",46048,5141146.29,15,11.71},{#datetime(2026,2,15,0,0,0),"FI","secure_corp",26602,1989420.47,34,6.92},{#datetime(2026,2,15,0,0,0),"FI","mit",36310,4378808.95,15,6.35},{#datetime(2026,2,15,0,0,0),"FI","contactless_lv",97254,3387424.67,23,8.71},{#datetime(2026,2,15,0,0,0),"FI","unattended",32199,2796429.86,23,7.47},{#datetime(2026,2,15,0,0,0),"EE","sca_applied",190624,8916196.99,231,4.16},{#datetime(2026,2,15,0,0,0),"EE","low_value",90997,13547091.96,92,3.94},{#datetime(2026,2,15,0,0,0),"EE","tra",80413,7307793.69,61,6.13},{#datetime(2026,2,15,0,0,0),"EE","trusted",46630,3076415.19,51,4.74},{#datetime(2026,2,15,0,0,0),"EE","recurring",80130,3457825.41,52,4.04},{#datetime(2026,2,15,0,0,0),"EE","corporate",52768,7105251.86,47,7.36},{#datetime(2026,2,15,0,0,0),"EE","secure_corp",19339,2824477.23,20,9.43},{#datetime(2026,2,15,0,0,0),"EE","mit",53732,3079113.4,13,6.03},{#datetime(2026,2,15,0,0,0),"EE","contactless_lv",101330,10688601.74,89,10.17},{#datetime(2026,2,15,0,0,0),"EE","unattended",8196,1054013.87,4,7.08},{#datetime(2026,3,15,0,0,0),"SE","sca_applied",250219,10806309.84,54,4.11},{#datetime(2026,3,15,0,0,0),"SE","low_value",44160,3513184.87,18,6.27},{#datetime(2026,3,15,0,0,0),"SE","tra",134020,18824837.87,155,8.96},{#datetime(2026,3,15,0,0,0),"SE","trusted",10109,1159404.85,7,6.95},{#datetime(2026,3,15,0,0,0),"SE","recurring",78893,6895610.54,48,11.5},{#datetime(2026,3,15,0,0,0),"SE","corporate",35280,4920013.96,20,4.57},{#datetime(2026,3,15,0,0,0),"SE","secure_corp",47994,6436841.53,45,9.74},{#datetime(2026,3,15,0,0,0),"SE","mit",27991,2888916.69,11,3.33},{#datetime(2026,3,15,0,0,0),"SE","contactless_lv",107042,7045496.45,131,11.8},{#datetime(2026,3,15,0,0,0),"SE","unattended",30999,2005042.96,13,8.61},{#datetime(2026,3,15,0,0,0),"NO","sca_applied",126697,11095658.95,103,11.25},{#datetime(2026,3,15,0,0,0),"NO","low_value",154740,9719990.45,50,8.28},{#datetime(2026,3,15,0,0,0),"NO","tra",88855,12216760.6,55,4.47},{#datetime(2026,3,15,0,0,0),"NO","trusted",61960,7841272.57,32,3.81},{#datetime(2026,3,15,0,0,0),"NO","recurring",84438,3333928.66,103,8.04},{#datetime(2026,3,15,0,0,0),"NO","corporate",54217,4743415.48,23,6.69},{#datetime(2026,3,15,0,0,0),"NO","secure_corp",36114,4100374.95,13,7.58},{#datetime(2026,3,15,0,0,0),"NO","mit",54488,3199193.13,14,10.91},{#datetime(2026,3,15,0,0,0),"NO","contactless_lv",50952,5429117.94,13,5.25},{#datetime(2026,3,15,0,0,0),"NO","unattended",29031,2516618.77,27,2.08},{#datetime(2026,3,15,0,0,0),"DK","sca_applied",201848,29742088.48,74,8.01},{#datetime(2026,3,15,0,0,0),"DK","low_value",107042,9344136.42,44,11.59},{#datetime(2026,3,15,0,0,0),"DK","tra",77450,4976178.66,19,9.34},{#datetime(2026,3,15,0,0,0),"DK","trusted",53150,5256340.91,42,8.82},{#datetime(2026,3,15,0,0,0),"DK","recurring",12134,1693756.87,4,10.65},{#datetime(2026,3,15,0,0,0),"DK","corporate",16593,2357420.26,4,10.12},{#datetime(2026,3,15,0,0,0),"DK","secure_corp",48897,4373655.68,60,11.56},{#datetime(2026,3,15,0,0,0),"DK","mit",30054,4063576.64,6,7.03},{#datetime(2026,3,15,0,0,0),"DK","contactless_lv",30979,4380859.93,17,5.73},{#datetime(2026,3,15,0,0,0),"DK","unattended",26249,2498809.11,19,11.29},{#datetime(2026,3,15,0,0,0),"FI","sca_applied",186987,16111262.99,76,1.8},{#datetime(2026,3,15,0,0,0),"FI","low_value",46306,5451760.21,41,8.76},{#datetime(2026,3,15,0,0,0),"FI","tra",17611,2085074.09,18,7.03},{#datetime(2026,3,15,0,0,0),"FI","trusted",60808,3233752.81,53,7.85},{#datetime(2026,3,15,0,0,0),"FI","recurring",51467,6651512.61,39,1.5},{#datetime(2026,3,15,0,0,0),"FI","corporate",49077,2034045.77,63,5.99},{#datetime(2026,3,15,0,0,0),"FI","secure_corp",18350,565552.17,11,5.64},{#datetime(2026,3,15,0,0,0),"FI","mit",28207,4075489.11,14,8.81},{#datetime(2026,3,15,0,0,0),"FI","contactless_lv",14802,908639.63,8,3.22},{#datetime(2026,3,15,0,0,0),"FI","unattended",27217,1202657.68,15,5.16},{#datetime(2026,3,15,0,0,0),"EE","sca_applied",186441,26245863.12,219,9.35},{#datetime(2026,3,15,0,0,0),"EE","low_value",148656,6554246.86,179,3.89},{#datetime(2026,3,15,0,0,0),"EE","tra",134634,7607098.9,168,6},{#datetime(2026,3,15,0,0,0),"EE","trusted",38755,4640109.58,33,5.28},{#datetime(2026,3,15,0,0,0),"EE","recurring",66823,9324137.48,68,9.72},{#datetime(2026,3,15,0,0,0),"EE","corporate",59369,3337079.56,28,9.18},{#datetime(2026,3,15,0,0,0),"EE","secure_corp",48864,1945976.87,34,8.59},{#datetime(2026,3,15,0,0,0),"EE","mit",12686,1776987.93,4,10.03},{#datetime(2026,3,15,0,0,0),"EE","contactless_lv",98167,5326426.93,77,2.39},{#datetime(2026,3,15,0,0,0),"EE","unattended",21824,1811855.24,21,8.74},{#datetime(2026,4,15,0,0,0),"SE","sca_applied",182030,7447399.85,138,9.8},{#datetime(2026,4,15,0,0,0),"SE","low_value",102725,4708234.92,67,6.98},{#datetime(2026,4,15,0,0,0),"SE","tra",123755,10579227.74,134,8.82},{#datetime(2026,4,15,0,0,0),"SE","trusted",34449,2085382.38,7,3.01},{#datetime(2026,4,15,0,0,0),"SE","recurring",15952,565239.98,9,1.23},{#datetime(2026,4,15,0,0,0),"SE","corporate",8988,1277671.83,2,11.24},{#datetime(2026,4,15,0,0,0),"SE","secure_corp",6112,393908.54,2,2.06},{#datetime(2026,4,15,0,0,0),"SE","mit",58981,8693868.01,53,5.33},{#datetime(2026,4,15,0,0,0),"SE","contactless_lv",77411,6488939.84,93,4.84},{#datetime(2026,4,15,0,0,0),"SE","unattended",5726,640900.72,5,6.7},{#datetime(2026,4,15,0,0,0),"NO","sca_applied",235085,31321451.45,76,11.92},{#datetime(2026,4,15,0,0,0),"NO","low_value",91016,8506486.99,90,3.06},{#datetime(2026,4,15,0,0,0),"NO","tra",15543,1876723.27,19,5.82},{#datetime(2026,4,15,0,0,0),"NO","trusted",58023,5531518.12,45,9.97},{#datetime(2026,4,15,0,0,0),"NO","recurring",34590,2949683.9,12,2.67},{#datetime(2026,4,15,0,0,0),"NO","corporate",52748,6427804.29,12,8.09},{#datetime(2026,4,15,0,0,0),"NO","secure_corp",39107,4768207.47,46,0.68},{#datetime(2026,4,15,0,0,0),"NO","mit",23202,883415.21,19,5.63},{#datetime(2026,4,15,0,0,0),"NO","contactless_lv",126267,14444272.72,31,9.02},{#datetime(2026,4,15,0,0,0),"NO","unattended",17505,1447225.05,14,9.18},{#datetime(2026,4,15,0,0,0),"DK","sca_applied",274553,10096213.15,206,3.83},{#datetime(2026,4,15,0,0,0),"DK","low_value",172993,24213405.17,144,7.14},{#datetime(2026,4,15,0,0,0),"DK","tra",165406,18311057.09,91,3.97},{#datetime(2026,4,15,0,0,0),"DK","trusted",16016,2374918.77,12,5.26},{#datetime(2026,4,15,0,0,0),"DK","recurring",37543,1400915.99,46,10.62},{#datetime(2026,4,15,0,0,0),"DK","corporate",16551,1739785.39,11,6.2},{#datetime(2026,4,15,0,0,0),"DK","secure_corp",23803,3403541.95,22,9.54},{#datetime(2026,4,15,0,0,0),"DK","mit",32459,3685920.93,21,3.95},{#datetime(2026,4,15,0,0,0),"DK","contactless_lv",43900,5291263.4,31,10.27},{#datetime(2026,4,15,0,0,0),"DK","unattended",13791,1832924.99,5,5.82},{#datetime(2026,4,15,0,0,0),"FI","sca_applied",43134,4204994.43,54,6.91},{#datetime(2026,4,15,0,0,0),"FI","low_value",40797,3125501.61,19,4.3},{#datetime(2026,4,15,0,0,0),"FI","tra",30273,4258473.26,34,1.56},{#datetime(2026,4,15,0,0,0),"FI","trusted",58423,7567460.65,14,4.84},{#datetime(2026,4,15,0,0,0),"FI","recurring",72776,7448706.04,84,2.66},{#datetime(2026,4,15,0,0,0),"FI","corporate",55162,5544348.65,52,3},{#datetime(2026,4,15,0,0,0),"FI","secure_corp",16135,2167488.54,9,11.51},{#datetime(2026,4,15,0,0,0),"FI","mit",7528,417200.2,3,9.03},{#datetime(2026,4,15,0,0,0),"FI","contactless_lv",138898,20827501.96,100,3.29},{#datetime(2026,4,15,0,0,0),"FI","unattended",24899,2849737.47,16,3.25},{#datetime(2026,4,15,0,0,0),"EE","sca_applied",128169,15772683.11,79,6.64},{#datetime(2026,4,15,0,0,0),"EE","low_value",84462,5659863.26,50,10.65},{#datetime(2026,4,15,0,0,0),"EE","tra",105674,4420646.95,134,5.9},{#datetime(2026,4,15,0,0,0),"EE","trusted",28926,4041530.09,17,5.26},{#datetime(2026,4,15,0,0,0),"EE","recurring",68242,9123337.92,69,0.69},{#datetime(2026,4,15,0,0,0),"EE","corporate",41445,5892212.59,35,5.3},{#datetime(2026,4,15,0,0,0),"EE","secure_corp",12939,692804.06,6,7.05},{#datetime(2026,4,15,0,0,0),"EE","mit",26460,2379182.73,24,8.38},{#datetime(2026,4,15,0,0,0),"EE","contactless_lv",56293,6845453.77,41,8.82},{#datetime(2026,4,15,0,0,0),"EE","unattended",29844,2652289.45,11,9.64},{#datetime(2026,5,15,0,0,0),"SE","sca_applied",79095,3701249.39,61,2.62},{#datetime(2026,5,15,0,0,0),"SE","low_value",119926,17849630.92,149,6.53},{#datetime(2026,5,15,0,0,0),"SE","tra",178370,23474113.52,220,8.18},{#datetime(2026,5,15,0,0,0),"SE","trusted",61323,1886674.46,21,7.75},{#datetime(2026,5,15,0,0,0),"SE","recurring",15410,1770042.49,2,6.32},{#datetime(2026,5,15,0,0,0),"SE","corporate",29589,1102297.3,27,11.24},{#datetime(2026,5,15,0,0,0),"SE","secure_corp",31655,3453983.54,6,6.62},{#datetime(2026,5,15,0,0,0),"SE","mit",40067,1259002.56,31,3.66},{#datetime(2026,5,15,0,0,0),"SE","contactless_lv",61247,1963404.01,67,8.25},{#datetime(2026,5,15,0,0,0),"SE","unattended",32279,4608367.96,13,11.06},{#datetime(2026,5,15,0,0,0),"NO","sca_applied",193485,9261663.42,79,6.55},{#datetime(2026,5,15,0,0,0),"NO","low_value",172882,12539632,185,1.41},{#datetime(2026,5,15,0,0,0),"NO","tra",93985,7996250.33,43,8.52},{#datetime(2026,5,15,0,0,0),"NO","trusted",27448,3076546.23,31,8.02},{#datetime(2026,5,15,0,0,0),"NO","recurring",77575,9398256.62,23,4.86},{#datetime(2026,5,15,0,0,0),"NO","corporate",41404,3607174.21,37,8.58},{#datetime(2026,5,15,0,0,0),"NO","secure_corp",8994,809337.43,6,9.52},{#datetime(2026,5,15,0,0,0),"NO","mit",52764,7771043.78,66,10.79},{#datetime(2026,5,15,0,0,0),"NO","contactless_lv",20053,1154495.76,23,8.46},{#datetime(2026,5,15,0,0,0),"NO","unattended",23523,2047897.01,6,1.36},{#datetime(2026,5,15,0,0,0),"DK","sca_applied",114886,15844792.14,93,0.88},{#datetime(2026,5,15,0,0,0),"DK","low_value",75780,2415800.13,31,2.16},{#datetime(2026,5,15,0,0,0),"DK","tra",174788,20192482.44,112,1.38},{#datetime(2026,5,15,0,0,0),"DK","trusted",17416,1701089.57,14,10.27},{#datetime(2026,5,15,0,0,0),"DK","recurring",80475,11072002.12,45,9.19},{#datetime(2026,5,15,0,0,0),"DK","corporate",14234,1777300.08,14,1.4},{#datetime(2026,5,15,0,0,0),"DK","secure_corp",46492,6830606.43,12,5.53},{#datetime(2026,5,15,0,0,0),"DK","mit",75181,2941248.3,65,7.56},{#datetime(2026,5,15,0,0,0),"DK","contactless_lv",113373,8798258.4,118,0.84},{#datetime(2026,5,15,0,0,0),"DK","unattended",12789,1586108.18,9,3.12},{#datetime(2026,5,15,0,0,0),"FI","sca_applied",202713,28975154.94,135,8.32},{#datetime(2026,5,15,0,0,0),"FI","low_value",142913,10805470.67,149,3.9},{#datetime(2026,5,15,0,0,0),"FI","tra",62890,7268367.98,18,2.27},{#datetime(2026,5,15,0,0,0),"FI","trusted",57481,7131525.5,21,4.98},{#datetime(2026,5,15,0,0,0),"FI","recurring",46682,1997335.58,9,4.05},{#datetime(2026,5,15,0,0,0),"FI","corporate",28714,3484815.62,9,1.5},{#datetime(2026,5,15,0,0,0),"FI","secure_corp",28700,2406827.8,23,5.19},{#datetime(2026,5,15,0,0,0),"FI","mit",8427,343425.16,6,7.36},{#datetime(2026,5,15,0,0,0),"FI","contactless_lv",145235,10011300.84,90,3.86},{#datetime(2026,5,15,0,0,0),"FI","unattended",16976,2096510.49,17,6.93},{#datetime(2026,5,15,0,0,0),"EE","sca_applied",102763,10136074.86,39,4.88},{#datetime(2026,5,15,0,0,0),"EE","low_value",41719,2597862.84,19,2.18},{#datetime(2026,5,15,0,0,0),"EE","tra",47449,3898472.79,31,6.07},{#datetime(2026,5,15,0,0,0),"EE","trusted",11177,819650.5,13,8.79},{#datetime(2026,5,15,0,0,0),"EE","recurring",61114,6188229.72,25,1.73},{#datetime(2026,5,15,0,0,0),"EE","corporate",25077,772667.15,16,10.18},{#datetime(2026,5,15,0,0,0),"EE","secure_corp",25809,3264602.98,14,4.35},{#datetime(2026,5,15,0,0,0),"EE","mit",73275,9439635.72,67,7.34},{#datetime(2026,5,15,0,0,0),"EE","contactless_lv",63567,4353047.98,79,2.81},{#datetime(2026,5,15,0,0,0),"EE","unattended",14283,732951.86,9,4.17},{#datetime(2026,6,15,0,0,0),"SE","sca_applied",261285,29628377.12,192,7.12},{#datetime(2026,6,15,0,0,0),"SE","low_value",61806,4271215.94,31,9.54},{#datetime(2026,6,15,0,0,0),"SE","tra",85994,3755079.26,70,7.31},{#datetime(2026,6,15,0,0,0),"SE","trusted",45368,2340612.68,47,0.81},{#datetime(2026,6,15,0,0,0),"SE","recurring",85835,7329885.65,84,5.54},{#datetime(2026,6,15,0,0,0),"SE","corporate",24199,3139962.19,7,10.25},{#datetime(2026,6,15,0,0,0),"SE","secure_corp",49298,3899333.84,37,7.78},{#datetime(2026,6,15,0,0,0),"SE","mit",26155,1577737.01,9,5.37},{#datetime(2026,6,15,0,0,0),"SE","contactless_lv",76484,2973384.34,98,6.01},{#datetime(2026,6,15,0,0,0),"SE","unattended",17452,1642613.42,21,10.5},{#datetime(2026,6,15,0,0,0),"NO","sca_applied",159313,15172555.39,170,4.63},{#datetime(2026,6,15,0,0,0),"NO","low_value",172317,16271648.93,155,1.48},{#datetime(2026,6,15,0,0,0),"NO","tra",164707,9847459.79,153,2.41},{#datetime(2026,6,15,0,0,0),"NO","trusted",50259,1774941.84,64,8.29},{#datetime(2026,6,15,0,0,0),"NO","recurring",50839,7423416.69,29,9.66},{#datetime(2026,6,15,0,0,0),"NO","corporate",11996,375063.2,6,6.37},{#datetime(2026,6,15,0,0,0),"NO","secure_corp",33668,3264465.13,32,3.04},{#datetime(2026,6,15,0,0,0),"NO","mit",37009,2847359.34,38,7.27},{#datetime(2026,6,15,0,0,0),"NO","contactless_lv",97320,4680057.65,126,6.05},{#datetime(2026,6,15,0,0,0),"NO","unattended",13597,1086633.11,17,1.83},{#datetime(2026,6,15,0,0,0),"DK","sca_applied",259764,12209156.6,140,5.74},{#datetime(2026,6,15,0,0,0),"DK","low_value",54910,5081070.13,31,1.62},{#datetime(2026,6,15,0,0,0),"DK","tra",155557,17673023.35,85,3.95},{#datetime(2026,6,15,0,0,0),"DK","trusted",64668,7455752.49,14,4.45},{#datetime(2026,6,15,0,0,0),"DK","recurring",19833,2206519.28,7,11.81},{#datetime(2026,6,15,0,0,0),"DK","corporate",21078,1937483.18,17,4.31},{#datetime(2026,6,15,0,0,0),"DK","secure_corp",28439,4124154.72,13,5.16},{#datetime(2026,6,15,0,0,0),"DK","mit",21425,1121939.39,19,5.05},{#datetime(2026,6,15,0,0,0),"DK","contactless_lv",137296,14236621.98,57,7.31},{#datetime(2026,6,15,0,0,0),"DK","unattended",17014,519496.62,7,3.7},{#datetime(2026,6,15,0,0,0),"FI","sca_applied",251263,31922370.1,66,1.67},{#datetime(2026,6,15,0,0,0),"FI","low_value",118909,6235040.25,65,5.76},{#datetime(2026,6,15,0,0,0),"FI","tra",65990,7290803.37,48,11.61},{#datetime(2026,6,15,0,0,0),"FI","trusted",28428,2889309.69,24,7.25},{#datetime(2026,6,15,0,0,0),"FI","recurring",45318,3273656.12,32,2.48},{#datetime(2026,6,15,0,0,0),"FI","corporate",49362,5662741.82,26,7.57},{#datetime(2026,6,15,0,0,0),"FI","secure_corp",9111,1008196.14,5,3.24},{#datetime(2026,6,15,0,0,0),"FI","mit",15878,825106.25,15,6.37},{#datetime(2026,6,15,0,0,0),"FI","contactless_lv",83445,8475587.87,68,5.36},{#datetime(2026,6,15,0,0,0),"FI","unattended",20592,2188138.12,20,7.92},{#datetime(2026,6,15,0,0,0),"EE","sca_applied",80375,7763410.6,59,2.11},{#datetime(2026,6,15,0,0,0),"EE","low_value",75798,9932451.16,67,10.45},{#datetime(2026,6,15,0,0,0),"EE","tra",16734,1475166.55,6,4.92},{#datetime(2026,6,15,0,0,0),"EE","trusted",46532,4218258.94,35,8.37},{#datetime(2026,6,15,0,0,0),"EE","recurring",52550,6054658.83,36,2.42},{#datetime(2026,6,15,0,0,0),"EE","corporate",42240,1423628.86,44,3.86},{#datetime(2026,6,15,0,0,0),"EE","secure_corp",19867,1132033.8,10,9.48},{#datetime(2026,6,15,0,0,0),"EE","mit",52747,6282282.23,55,6.82},{#datetime(2026,6,15,0,0,0),"EE","contactless_lv",31975,3156778.72,15,6.75},{#datetime(2026,6,15,0,0,0),"EE","unattended",16210,1540680.49,16,9.24}}), Typed = Table.TransformColumnTypes(Source,{{"kpi_date", type datetime},{"issuer_country", type text},{"sca_exemption_code", type text},{"tx_count", Int64.Type},{"tx_value_eur", type number},{"fraud_count", Int64.Type},{"fraud_rate_bps", type number}}) in Typed

