table Fact_Eba
	lineageTag: fact-eba

	column Quarter
		dataType: string
		lineageTag: e1c01e7f-40b3-47a6-8afc-2f857d01996f
		summarizeBy: none
		sourceColumn: quarter

	column CountryCode
		dataType: string
		lineageTag: 86418a36-c69e-4157-a4f7-ca3e91e8c0d7
		summarizeBy: none
		sourceColumn: reporting_country

	column Instrument
		dataType: string
		lineageTag: f4bbdd59-1d44-4cfb-8596-db6429dbc6d2
		summarizeBy: none
		sourceColumn: instrument

	column Channel
		dataType: string
		lineageTag: 0a69fe38-a150-4b70-9ec1-fc2e156e004f
		summarizeBy: none
		sourceColumn: channel

	column ExemptionCode
		dataType: string
		lineageTag: 75f3b647-f4e7-4c10-91cc-b5fc0cdb5f89
		summarizeBy: none
		sourceColumn: sca_exemption

	column FraudTypeCode
		dataType: string
		lineageTag: 9b7a65ee-c9ca-4484-aabb-9b586587c58b
		summarizeBy: none
		sourceColumn: fraud_type

	column CounterpartyGeo
		dataType: string
		lineageTag: 4f522960-dc7f-4926-9216-c596d8269e95
		summarizeBy: none
		sourceColumn: counterparty_geo

	column LossBearer
		dataType: string
		lineageTag: 2aaf3ce7-fba9-4002-948f-08d251c1da04
		summarizeBy: none
		sourceColumn: loss_bearer

	column TxCount
		dataType: int64
		lineageTag: 352e8560-dea1-4037-aac4-e9197dca69e1
		summarizeBy: sum
		sourceColumn: tx_count

	column TxValueEur
		dataType: double
		formatString: "€"#,0.00
		lineageTag: ce4448cc-c651-49b5-82c5-1ff0778574cd
		summarizeBy: sum
		sourceColumn: tx_value_eur

	column FraudCount
		dataType: int64
		lineageTag: fa650ba6-5cf6-4ee1-9b15-d9ac9a4a8dd0
		summarizeBy: sum
		sourceColumn: fraud_count

	column FraudValueEur
		dataType: double
		formatString: "€"#,0.00
		lineageTag: 14e3b6d7-e3ff-486d-a7ff-6e6965461262
		summarizeBy: sum
		sourceColumn: fraud_value_eur

	column LossValueEur
		dataType: double
		formatString: "€"#,0.00
		lineageTag: f1ba1c4a-80b5-4d86-9d3f-9c6d0d890751
		summarizeBy: sum
		sourceColumn: loss_value_eur

	partition Fact_Eba = m
		mode: import
		source = let Source = #table({"quarter","reporting_country","instrument","channel","sca_exemption","fraud_type","counterparty_geo","loss_bearer","tx_count","tx_value_eur","fraud_count","fraud_value_eur","loss_value_eur"},{{"2024-Q3","SE","card","pos","tra","unauthorised_modification","domestic","merchant",575876,61890197.73,239,48399.06,33054.82},{"2024-Q3","SE","credit_transfer","moto","recurring","lost_stolen","eea","merchant",601126,91099362.7,296,103358.24,48739.49},{"2024-Q3","SE","direct_debit","ecommerce","mit","manipulation_of_payer","non_eea","payer",209853,42349077.38,141,45993.38,30967.3},{"2024-Q3","NO","card","moto","mit","unauthorised_issuance","domestic","payer",869975,185448423.67,741,284717.74,156896.8},{"2024-Q3","NO","credit_transfer","moto","recurring","unauthorised_issuance","non_eea","merchant",799704,83659153.35,429,92863.58,38164.13},{"2024-Q3","NO","direct_debit","pos","unattended","other","eea","psp",251426,51268540.08,225,101675.68,86573.53},{"2024-Q3","DK","card","pos","low_value","counterfeit","non_eea","psp",867542,64392227.52,434,68650.49,53803.82},{"2024-Q3","DK","credit_transfer","atm","corporate","counterfeit","eea","psp",523939,95330641.91,171,52934.75,24652.03},{"2024-Q3","DK","direct_debit","atm","tra","manipulation_of_payer","eea","payer",410548,26188349.32,300,45327.76,30162.28},{"2024-Q3","FI","card","pos","secure_corp","other","non_eea","payer",555168,102573870.6,374,95554.8,74253.32},{"2024-Q3","FI","credit_transfer","atm","unattended","lost_stolen","non_eea","payer",294689,53728510.16,91,31361.5,19675.99},{"2024-Q3","FI","direct_debit","atm","unattended","unauthorised_modification","non_eea","psp",313609,50638627.11,212,67830.29,59119.83},{"2024-Q3","EE","card","pos","sca_applied","unauthorised_issuance","eea","payer",866269,163113223.25,890,273561.79,165271.79},{"2024-Q3","EE","credit_transfer","moto","unattended","counterfeit","non_eea","psp",321761,18499507.04,324,26996.61,16922.07},{"2024-Q3","EE","direct_debit","atm","sca_applied","counterfeit","eea","psp",635037,100263414.66,614,191675.35,166666.8},{"2024-Q4","SE","card","atm","contactless_lv","counterfeit","eea","psp",664920,79820490.8,325,66284.22,59023.7},{"2024-Q4","SE","credit_transfer","ecommerce","trusted","counterfeit","non_eea","merchant",617479,55362339.32,663,139330.77,113149.9},{"2024-Q4","SE","direct_debit","pos","low_value","other","non_eea","psp",222394,10920464.31,126,14773.01,11722.22},{"2024-Q4","NO","card","ecommerce","recurring","other","domestic","psp",814867,64269573.45,811,106271.74,50349.12},{"2024-Q4","NO","credit_transfer","ecommerce","corporate","other","domestic","merchant",766456,65239014.34,336,57975.99,23937.71},{"2024-Q4","NO","direct_debit","ecommerce","low_value","lost_stolen","eea","payer",539498,23112415.34,276,17019.88,10390.3},{"2024-Q4","DK","card","atm","mit","counterfeit","domestic","psp",738169,108407413.13,488,110633.65,78279.22},{"2024-Q4","DK","credit_transfer","moto","low_value","unauthorised_issuance","eea","merchant",702248,135192387.32,450,122908.68,92943.62},{"2024-Q4","DK","direct_debit","atm","secure_corp","card_not_received","non_eea","payer",355539,18425027.2,184,19036.31,12833.87},{"2024-Q4","FI","card","pos","secure_corp","lost_stolen","domestic","payer",675755,88523359.94,435,123793.78,56599.39},{"2024-Q4","FI","credit_transfer","atm","recurring","manipulation_of_payer","domestic","merchant",555395,104933810.06,343,136257.0,75796.25},{"2024-Q4","FI","direct_debit","atm","tra","card_not_received","domestic","merchant",697305,36318430.46,673,49163.03,22038.91},{"2024-Q4","EE","card","moto","sca_applied","manipulation_of_payer","non_eea","payer",788866,111311366.05,659,162902.74,136317.61},{"2024-Q4","EE","credit_transfer","ecommerce","corporate","other","non_eea","payer",568727,33354759.03,401,34576.08,22166.54},{"2024-Q4","EE","direct_debit","ecommerce","unattended","counterfeit","non_eea","payer",320465,56808514.49,243,94248.66,77526.83},{"2025-Q1","SE","card","ecommerce","tra","other","domestic","merchant",230359,16695243.87,198,23532.37,13411.39},{"2025-Q1","SE","credit_transfer","pos","secure_corp","lost_stolen","eea","payer",889275,99724349.55,367,82167.14,34126.36},{"2025-Q1","SE","direct_debit","ecommerce","sca_applied","unauthorised_modification","domestic","merchant",365055,38918351.7,320,73501.55,50260.12},{"2025-Q1","NO","card","moto","secure_corp","manipulation_of_payer","domestic","merchant",252179,40680095.99,130,42531.7,27340.69},{"2025-Q1","NO","credit_transfer","atm","sca_applied","unauthorised_modification","eea","merchant",319346,32615162.73,124,25911.57,18049.15},{"2025-Q1","NO","direct_debit","atm","recurring","manipulation_of_payer","domestic","psp",257443,10653937.56,139,8814.63,4130.69},{"2025-Q1","DK","card","atm","low_value","lost_stolen","non_eea","psp",721546,125882749.49,317,95025.97,71443.91},{"2025-Q1","DK","credit_transfer","moto","secure_corp","manipulation_of_payer","domestic","payer",657409,28514113.87,681,66409.42,45681.68},{"2025-Q1","DK","direct_debit","atm","low_value","lost_stolen","domestic","psp",221869,47461316.66,97,48603.94,30622.84},{"2025-Q1","FI","card","atm","trusted","manipulation_of_payer","domestic","psp",656839,95896413.06,472,119583.39,66385.2},{"2025-Q1","FI","credit_transfer","atm","tra","unauthorised_modification","domestic","psp",735280,113218737.96,532,123965.41,97698.89},{"2025-Q1","FI","direct_debit","pos","mit","lost_stolen","non_eea","merchant",468402,35368531.26,366,59037.61,42964.89},{"2025-Q1","EE","card","atm","corporate","unauthorised_modification","eea","psp",670711,109060308.95,674,219989.29,196508.95},{"2025-Q1","EE","credit_transfer","ecommerce","recurring","lost_stolen","eea","psp",691699,82725437.6,375,71854.49,30759.91},{"2025-Q1","EE","direct_debit","ecommerce","unattended","card_not_received","non_eea","payer",259653,27620008.31,137,29279.24,26020.0},{"2025-Q2","SE","card","pos","corporate","card_not_received","eea","merchant",685188,98981774.28,728,222196.88,93436.31},{"2025-Q2","SE","credit_transfer","ecommerce","contactless_lv","counterfeit","domestic","psp",358189,76075770.52,236,109875.09,89953.48},{"2025-Q2","SE","direct_debit","atm","corporate","manipulation_of_payer","eea","payer",459778,76953920.55,502,157662.77,111136.91},{"2025-Q2","NO","card","atm","low_value","card_not_received","non_eea","payer",554803,89989928.57,189,61127.51,34679.14},{"2025-Q2","NO","credit_transfer","pos","corporate","unauthorised_issuance","non_eea","merchant",497949,42504548.84,488,98341.98,68972.19},{"2025-Q2","NO","direct_debit","pos","unattended","counterfeit","domestic","payer",348298,71406092.22,190,78749.18,57570.97},{"2025-Q2","DK","card","ecommerce","secure_corp","card_not_received","eea","psp",786072,84740349.98,733,173407.6,127464.68},{"2025-Q2","DK","credit_transfer","pos","trusted","unauthorised_modification","domestic","psp",580211,55465788.45,615,98528.96,77155.87},{"2025-Q2","DK","direct_debit","ecommerce","corporate","other","non_eea","psp",510160,97949245.62,194,80006.09,65409.77},{"2025-Q2","FI","card","pos","mit","unauthorised_issuance","eea","payer",826258,89078525.26,355,84753.45,66577.98},{"2025-Q2","FI","credit_transfer","pos","contactless_lv","unauthorised_modification","eea","payer",449068,96336738.69,354,161576.89,127952.77},{"2025-Q2","FI","direct_debit","atm","secure_corp","card_not_received","non_eea","payer",403440,42849916.11,426,107816.07,68014.69},{"2025-Q2","EE","card","moto","corporate","card_not_received","domestic","merchant",369930,69191863.73,348,94526.29,49626.45},{"2025-Q2","EE","credit_transfer","pos","secure_corp","unauthorised_issuance","domestic","payer",740970,143162731.2,391,161623.27,86694.02},{"2025-Q2","EE","direct_debit","moto","low_value","manipulation_of_payer","domestic","psp",566566,117553916.42,358,128956.79,75695.15}}), Typed = Table.TransformColumnTypes(Source,{{"quarter", type text},{"reporting_country", type text},{"instrument", type text},{"channel", type text},{"sca_exemption", type text},{"fraud_type", type text},{"counterparty_geo", type text},{"loss_bearer", type text},{"tx_count", Int64.Type},{"tx_value_eur", type number},{"fraud_count", Int64.Type},{"fraud_value_eur", type number},{"loss_value_eur", type number}}) in Typed

